unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DSA_Connector__c</fullName>
        <label>DSA / Connector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DSA</fullName>
                </value>
                <value>
                    <fullName>Connector</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Collection_Task__c.object
<CustomObject>
    <fields>
        <fullName>Loan_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Account</label>
        <referenceTo>Loan_Account__c</referenceTo>
        <relationshipLabel>Collection Tasks</relationshipLabel>
        <relationshipName>Collection_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete - Overdue amount Pending</fullName>
                </value>
                <value>
                    <fullName>Complete - Fully Recovered</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Collection Task</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Collection #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Task</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open - Lead</fullName>
                </value>
                <value>
                    <fullName>Appointment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Appointment Re-schdeduled</fullName>
                </value>
                <value>
                    <fullName>CIBIL Updated</fullName>
                </value>
                <value>
                    <fullName>Under Qualification process</fullName>
                </value>
                <value>
                    <fullName>Documentation in process</fullName>
                </value>
                <value>
                    <fullName>Sales Team Qualified</fullName>
                </value>
                <value>
                    <fullName>SM Queue</fullName>
                </value>
                <value>
                    <fullName>Sales Co-ordinator Queue</fullName>
                </value>
                <value>
                    <fullName>BM Queue</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Not Contactable</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>Document Processing</fullName>
                    <isActive>false</isActive>
                    <label>Document Processing</label>
                </value>
                <value>
                    <fullName>Document Verification</fullName>
                    <isActive>false</isActive>
                    <label>Document Verification</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                    <isActive>false</isActive>
                    <label>Prospecting</label>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                    <isActive>false</isActive>
                    <label>Qualification</label>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <isActive>false</isActive>
                    <label>Qualified</label>
                </value>
                <value>
                    <fullName>Quote Sent</fullName>
                    <isActive>false</isActive>
                    <label>Quote Sent</label>
                </value>
                <value>
                    <fullName>Underwriting</fullName>
                    <isActive>false</isActive>
                    <label>Underwriting</label>
                </value>
                <value>
                    <fullName>Working</fullName>
                    <isActive>false</isActive>
                    <label>Working</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Loan_Account__c.object
<CustomObject>
    <description>will be used to store loan and EMI related information</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Loan Accounts (Lead)</relationshipLabel>
        <relationshipName>Loan_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DSA_Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DSA/Connector</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Accounts</relationshipLabel>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for loan if any is Pending or loan is fully paid</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applied</fullName>
                    <default>true</default>
                    <label>Applied</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Disbursed</fullName>
                </value>
                <value>
                    <fullName>EMI Scheduled</fullName>
                </value>
                <value>
                    <fullName>Pending Closure</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loan Account</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Meeting__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category </label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DSA</fullName>
                </value>
                <value>
                    <fullName>Connector</fullName>
                </value>
                <value>
                    <fullName>New Customer </fullName>
                </value>
                <value>
                    <fullName>Existing Customer</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Other Referral Source</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Check_Out_Location__c</fullName>
        <label>Check Out Location</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Collection_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection Task</label>
        <referenceTo>Collection_Task__c</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DSA_Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DSA/Connector</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Account</label>
        <referenceTo>Loan_Account__c</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_Details__c</fullName>
        <label>Meeting Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Meeting_Outcome__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Rate of Interest Issue</fullName>
                </value>
                <value>
                    <fullName>Loan Amount Issue</fullName>
                </value>
                <value>
                    <fullName>Tenor Issue</fullName>
                </value>
                <value>
                    <fullName>PF Issue</fullName>
                </value>
                <value>
                    <fullName>Insurance Cost</fullName>
                </value>
                <value>
                    <fullName>BT Cost</fullName>
                </value>
                <value>
                    <fullName>Documentation Issue</fullName>
                </value>
                <value>
                    <fullName>Client Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Property not acceptable</fullName>
                </value>
                <value>
                    <fullName>Policy norms not met</fullName>
                </value>
                <value>
                    <fullName>Negative Profile</fullName>
                </value>
                <value>
                    <fullName>Poor RTR</fullName>
                </value>
                <value>
                    <fullName>Poor Banking</fullName>
                </value>
                <value>
                    <fullName>Poor CIBIL</fullName>
                </value>
                <value>
                    <fullName>Rescheduled date</fullName>
                </value>
                <value>
                    <fullName>Rescheduled time</fullName>
                </value>
                <value>
                    <fullName>Customer Interested</fullName>
                </value>
                <value>
                    <fullName>Customer Not Interested</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Salesperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheduled_End_Time__c</fullName>
        <label>Scheduled End Time </label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scheduled_Start_Time__c</fullName>
        <label>Scheduled Start Time </label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Re-Scheduled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Collection Task </fullName>
                </value>
                <value>
                    <fullName>Meeting </fullName>
                </value>
                <value>
                    <fullName>Other </fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Meeting</label>
    <nameField>
        <displayFormat>MEET-{0000}</displayFormat>
        <label>Meeting #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/MeetingTriggerHandler.cls
public class MeetingTriggerHandler {
    public static void validationcheckonReScheduled(Map<Id,Meeting__c> OldMap,Map<Id,Meeting__c> NewMap){
        for(Meeting__c ma:newMap.values()){
            datetime da=system.now();
            if(ma.Status__c=='Re-Scheduled' && Oldmap.get(ma.Id).Status__c!='Re-Scheduled' && Oldmap.get(ma.Id).Scheduled_Start_Time__c==ma.Scheduled_Start_Time__c){
                ma.addError('Please enter a new Scheduled Start Time');
            }
            if(ma.Status__c!='Completed' && Oldmap.get(ma.Id).Status__c=='Completed'){
                ma.addError('Status of completed meetings cannot be changed');
            }
            
            if(ma.Status__c=='Scheduled' && Oldmap.get(ma.Id).Status__c=='Scheduled'){
                if(da>=ma.Scheduled_Start_Time__c){
                    ma.addError('Scheduled Meeting can not be added in back date');
                }  
            }
            if(ma.Status__c=='Completed'){
                
                if(ma.Type__c!=Oldmap.get(ma.Id).Type__c || ma.Category__c!=Oldmap.get(ma.Id).Category__c
                   || ma.Salesperson__c!=Oldmap.get(ma.Id).Salesperson__c || ma.OwnerId!=Oldmap.get(ma.Id).OwnerId||ma.Scheduled_Start_Time__c!=Oldmap.get(ma.Id).Scheduled_Start_Time__c
                   || ma.Scheduled_End_Time__c!=Oldmap.get(ma.Id).Scheduled_End_Time__c || ma.Scheduled_End_Time__c!=Oldmap.get(ma.Id).Scheduled_End_Time__c
                   || ma.Applicant__c!=Oldmap.get(ma.Id).Applicant__c || ma.Loan_Account__c!=Oldmap.get(ma.Id).Loan_Account__c || ma.Collection_Task__c!=Oldmap.get(ma.Id).Collection_Task__c ||
                   ma.DSA_Connector__c!=Oldmap.get(ma.Id).DSA_Connector__c) 
                {
                    
                    
                    ma.addError('On Completed Stage We Can Not Update Type,Category,Salesperson,Owner,Scheduled Start Time,Scheduled End Time,Applicant,Collection Task,Loan Account,DSA/Connector');
                }
                
            }
        }
        
        
    }
    
    public static void Ownerupdateoninsert(List<Meeting__c> newmeeting){
        for(Meeting__c ma:newmeeting){
            if(ma.Salesperson__c!=null){              
                ma.OwnerId=ma.Salesperson__c;           
                
            }
        }
    }
    
    public static void Ownerupdate(List<Meeting__c> newmeeting,Map<Id,Meeting__c> OldMap){
        for(Meeting__c ma:newmeeting){
            if(ma.Salesperson__c!=null && Oldmap.get(ma.Id).Salesperson__c!=ma.Salesperson__c){              
                ma.OwnerId=ma.Salesperson__c;           
                
            }
        }
    }
    
    public static void validationcheckonCompleted(Map<Id,Meeting__c> OldMap,Map<Id,Meeting__c> NewMap){
        
        for(Meeting__c ma:newMap.values()){
            
            if(ma.Status__c=='Completed' && ma.Meeting_Details__c==null && ma.Check_Out_Location__c!=null){
                ma.addError('Meeting Outcome is required to Complete the meeting');  
            }
            if(ma.Status__c=='Completed'&& ma.Status__c!=Oldmap.get(ma.Id).Status__c && ma.Applicant__c!=null){
                string phone_no;
                string customer_name;
                string salesperson_name=ma.owner_name__c;
                contact con=[select id,Name,MobilePhone from contact where id=:ma.Applicant__c limit 1];
                
                 phone_no = (String)con.get('MobilePhone');
                 customer_name = (String)con.get('Name');
                system.debug('phone_no--'+phone_no);
                system.debug('customer_name--'+customer_name);
                system.debug('salesperson_name--'+salesperson_name);
                if(customer_name!=null && salesperson_name!=null && phone_no!=null){
                    SendSmsFeedback(ma.Id,phone_no,salesperson_name,customer_name);
                }

                
            }
              
        }
        
    }
    
   
   /* public static void checkonrelatedmetting(List<Meeting__c> newmeeting){
        for(Meeting__c ma:newmeeting){
            
            if(ma.Category__c!='Other Referral Source'|| ma.Category__c!='Others'){
                if(ma.Applicant__c==null||ma.Loan_Account__c==null||ma.Collection_Task__c==null||ma.DSA_Connector__c==null){
                     ma.addError('Please select the record related to meeting');  
                }
            }
                //if(ma.Category__c=='Other Referral Source'|| ma.Category__c=='Others')
                system.debug('inside other'+ma.Category__c);
                if(ma.Category__c=='Others'){
                    system.debug('inside other'+ma.Category__c);
                    if(ma.Referral_Source__c==null){
                        
                        ma.addError('Please Enter the Referral Source'); 
                    }
                   
                
            }
            
            
            
        }
    }*/
        
        
    @future(callout=true)
    public static void SendSmsFeedback(id meetingid,string Phoneno,string salesperson_name,string customer_name ){
         string SMS_LOGIN_ID;
         string SMS_PASSWORD;
         string SMS_SENDER;
         string SMS_URL;
         string text;
         string dlr_mask;
         string to;
        string endpoint;
        
        List<SMS_Credential__mdt> sms=[select MasterLabel,SMS_LOGIN_ID__c,SMS_PASSWORD__c,SMS_SENDER__c,SMS_URL__c,dlr_mask__c from SMS_Credential__mdt LIMIT 1];
        SMS_LOGIN_ID=sms[0].SMS_LOGIN_ID__c;
        SMS_PASSWORD=sms[0].SMS_PASSWORD__c;
        SMS_SENDER=sms[0].SMS_SENDER__c;
        SMS_URL=sms[0].SMS_URL__c;
        dlr_mask=sms[0].dlr_mask__c;
        to=Phoneno;
        string AcknowledgementRequest=system.label.site_Url;
         string var1=customer_name;
        //string var2='<a href="https://dev-ambitportal.cs76.force.com/MeetingFeedback/Meeting_Feedback?id={!meetingid}">Click here to rate </a>';
       string var2=salesperson_name;
        string var3='https://dev-ambitportal.cs76.force.com/MeetingFeedback/Meeting_Feedback?id='+meetingid+'';
         string url= 'https://'+AcknowledgementRequest+'?id='+meetingid+'';
        system.debug('customer_name'+var1);
        system.debug('salesperson_name'+var2);
       system.debug('url'+url);
        string  testtext='Thanks '+var1+' for spending your valuable time with the sales executive of Ambit Finvest,'+var2+'. Kindly provide your feedback through the link below.'+url+'';
         system.debug('testtext->'+testtext);
        String encodedString = EncodingUtil.urlEncode(testtext,'UTF-8');
        encodedString = encodedString.replace ('+','%20');
        encodedString = encodedString.replace ('%3A',':');
        system.debug('encodedString->'+encodedString);
        
         endpoint='https://'+SMS_URL+'?username='+SMS_LOGIN_ID+'&password='+SMS_PASSWORD+'&to='+Phoneno+'&from='+SMS_SENDER+'&text='+encodedString+'&dlr-mask='+dlr_mask+'&dlr-url';
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        req.setMethod('GET');
        req.setEndpoint(endpoint);
        req.setTimeout(120000);
        res = h.send(req); 
        String responseBody = res.getBody();
        system.debug('response: '+responseBody);
    }
    
    
    
}