unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DSA_Connector__c</fullName>
        <label>DSA / Connector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DSA</fullName>
                </value>
                <value>
                    <fullName>Connector</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CIBIL_ID_Number__c</fullName>
        <label>CIBIL ID Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIBIL_ID__c</fullName>
        <label>CIBIL ID</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Driving License Number (Permanent only)</fullName>
                </value>
                <value>
                    <fullName>Passport Number</fullName>
                </value>
                <value>
                    <fullName>Voter ID Number</fullName>
                </value>
                <value>
                    <fullName>Pan No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lead - VYAPAR (SECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UDYAM (UNSECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UCV</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Vyapar</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Udyam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Of_Interest__c</fullName>
        <label>Rate Of Interest</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open - Lead</fullName>
                </value>
                <value>
                    <fullName>Appointment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Appointment Re-schdeduled</fullName>
                </value>
                <value>
                    <fullName>CIBIL Updated</fullName>
                </value>
                <value>
                    <fullName>Under Qualification process</fullName>
                </value>
                <value>
                    <fullName>Documentation in process</fullName>
                </value>
                <value>
                    <fullName>Sales Team Qualified</fullName>
                </value>
                <value>
                    <fullName>SM Queue</fullName>
                </value>
                <value>
                    <fullName>Sales Co-ordinator Queue</fullName>
                </value>
                <value>
                    <fullName>BM Queue</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Not Contactable</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>Document Processing</fullName>
                    <isActive>false</isActive>
                    <label>Document Processing</label>
                </value>
                <value>
                    <fullName>Document Verification</fullName>
                    <isActive>false</isActive>
                    <label>Document Verification</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                    <isActive>false</isActive>
                    <label>Prospecting</label>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                    <isActive>false</isActive>
                    <label>Qualification</label>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <isActive>false</isActive>
                    <label>Qualified</label>
                </value>
                <value>
                    <fullName>Quote Sent</fullName>
                    <isActive>false</isActive>
                    <label>Quote Sent</label>
                </value>
                <value>
                    <fullName>Underwriting</fullName>
                    <isActive>false</isActive>
                    <label>Underwriting</label>
                </value>
                <value>
                    <fullName>Working</fullName>
                    <isActive>false</isActive>
                    <label>Working</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Loan_Account__c.object
<CustomObject>
    <description>will be used to store loan and EMI related information</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Loan Accounts (Lead)</relationshipLabel>
        <relationshipName>Loan_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DPD__c</fullName>
        <label>DPD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DSA_Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DSA/Connector</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Accounts</relationshipLabel>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disbursal_Amount__c</fullName>
        <label>Disbursal Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Disbursal_Date__c</fullName>
        <label>Disbursal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LOAN_STATUS__c</fullName>
        <label>LOAN STATUS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROI__c</fullName>
        <label>ROI</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for loan if any is Pending or loan is fully paid</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applied</fullName>
                    <default>true</default>
                    <label>Applied</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Disbursed</fullName>
                </value>
                <value>
                    <fullName>EMI Scheduled</fullName>
                </value>
                <value>
                    <fullName>Pending Closure</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loan Account</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/SalesIncentiveRuralBatch_Test.cls
@isTest
public class SalesIncentiveRuralBatch_Test {
     Public static testmethod void SecuredMethod(){
         string recordtypeid =Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
         string product='Lead - Rural Vyapar';
         // create the applicant 
         Contact c1=TestDataFactory.CreateApplicant(recordtypeid, product);
         // create the Loan Account 
          Loan_Account__c la1 =TestDataFactory.CreatLoanAccount(c1.id,true);
         Loan_Account__c la2 =TestDataFactory.CreatLoanAccount(c1.id,false);
         la2.Disbursal_Amount__c=510000;
         insert la2;
         Test.startTest();
        SalesIncentiveRuralBatch obj = new SalesIncentiveRuralBatch();
        DataBase.executeBatch(obj); 
        Test.stopTest();    
     } 
     Public static testmethod void UnSecuredMethod(){
         string recordtypeid =Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
         string product='Lead - Rural Udyam';
         string dsaorconnector='DSA';
         string accrecordtypeid=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        
         // create the Dsa Account
        Account acc=TestDataFactory.CreateAccount(accrecordtypeid, dsaorconnector);
        
        // create the applicant-2 
        Contact c2=TestDataFactory.CreateApplicantbulk(recordtypeid, product,false);
        c2.FirstName = 'Test1';
        c2.LastName = 'Name1';
        c2.Email = 'test1@abc.com';
        c2.Phone = '865599442';
         c2.Loan_Amount__c=3500000;
         c2.Rate_Of_Interest__c=16;
        insert c2;
        // create the Loan Account 
        Loan_Account__c la1 =TestDataFactory.CreatLoanAccount(c2.id,false);
        la1.ROI__c=14;
         la1.Applicant__c=c2.Id;
         la1.Disbursal_Amount__c=null;
         la1.LOAN_STATUS__c='Disbursed';
         la1.DSA_Connector__c=acc.id;
        insert la1;
         Test.startTest();
        SalesIncentiveRuralBatch obj = new SalesIncentiveRuralBatch();
        DataBase.executeBatch(obj); 
        Test.stopTest();
     }
      Public static testmethod void UnSecuredMethod5abv(){
          string recordtypeid =Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
         string product='Lead - Rural Udyam';
          string dsaorconnector='DSA';
         string accrecordtypeid=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        
         // create the Dsa Account
        Account acc=TestDataFactory.CreateAccount(accrecordtypeid, dsaorconnector);
        
        // create the applicant 
         Contact c=TestDataFactory.CreateApplicant(recordtypeid, product);
        // create the Loan Account 
          Loan_Account__c la =TestDataFactory.CreatLoanAccount(c.id,false); 
        la.Applicant__c = c.id;
        la.DPD__c=0;
        la.Disbursal_Amount__c=50000;
        la.Disbursal_Date__c=system.today();
        la.LOAN_STATUS__c='Disbursed';
        la.DSA_Connector__c=acc.id;
           insert la;
       list<Contact> c1 = new list<Contact>();
         for (integer i=0; i<=5;i++){
             Contact app = new Contact();
        app.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        app.FirstName = 'Test'+i;
        app.LastName = 'Name'+i;
        app.Email = 'test+i@abc.com';
        app.Phone = '86559944'+i;
        app.Product__c = 'Lead - Rural Udyam';
        app.CIBIL_ID__c = 'Passport Number';
        app.CIBIL_ID_Number__c = '123';
        app.status__c = 'Prospect';
             c1.add(app);
         }
        insert c1;
        list<Loan_Account__c> loan = new list<Loan_Account__c>();
         for(integer i=0 ;i<=c1.size()-i;i++){
        Loan_Account__c la1 = new Loan_Account__c();
        la1.Applicant__c = c1[i].id;
        la1.DPD__c=0;
        la1.Disbursal_Amount__c=50000;
        la1.Disbursal_Date__c=system.today();
        la1.LOAN_STATUS__c='Disbursed';
        la1.DSA_Connector__c=acc.id;
             loan.add(la1);
         }
         
        insert loan;
         Test.startTest();
        SalesIncentiveRuralBatch obj = new SalesIncentiveRuralBatch();
        DataBase.executeBatch(obj); 
        Test.stopTest();    
     }
    
    Public static testmethod void UnSecuredMethodfor6abov(){
        string recordtypeid =Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
         string product='Lead - Rural Udyam';
        string dsaorconnector='DSA';
         string accrecordtypeid=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        
         // create the Dsa Account
        Account acc=TestDataFactory.CreateAccount(accrecordtypeid, dsaorconnector);
        
        // create the applicant 
         Contact c=TestDataFactory.CreateApplicant(recordtypeid, product);
        // create the Loan Account 
            Loan_Account__c la =TestDataFactory.CreatLoanAccount(c.id,false); 
        la.Applicant__c = c.id;
        la.DPD__c=0;
        la.Disbursal_Amount__c=50000;
        la.Disbursal_Date__c=system.today();
        la.LOAN_STATUS__c='Disbursed';
        la.DSA_Connector__c=acc.id;
           insert la;
         
       list<Contact> c1 = new list<Contact>();
         for (integer i=0; i<=7;i++){
             Contact app = new Contact();
        app.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        app.FirstName = 'Test'+i;
        app.LastName = 'Name'+i;
        app.Email = 'test+i@abc.com';
        app.Phone = '86559944'+i;
        app.Product__c = 'Lead - Rural Udyam';
        app.CIBIL_ID__c = 'Passport Number';
        app.CIBIL_ID_Number__c = '123';
        app.status__c = 'Prospect';
             c1.add(app);
         }
        
        insert c1;
        
        list<Loan_Account__c> loan = new list<Loan_Account__c>();
         for(integer i=0 ;i<=c1.size()-i;i++){
        Loan_Account__c la1 = new Loan_Account__c();
        la1.Applicant__c = c1[i].id;
        la1.DPD__c=0;
        la1.Disbursal_Amount__c=50000;
        la1.Disbursal_Date__c=system.today();
        la1.LOAN_STATUS__c='Disbursed';
        la1.DSA_Connector__c=acc.Id;
             loan.add(la1);
         }
         
        insert loan;
         
         Test.startTest();
        SalesIncentiveRuralBatch obj = new SalesIncentiveRuralBatch();
        DataBase.executeBatch(obj); 
        Test.stopTest();
         
        
     }       

}