unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DSA_Connector__c</fullName>
        <label>DSA / Connector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DSA</fullName>
                </value>
                <value>
                    <fullName>Connector</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Loan_Account__c.object
<CustomObject>
    <description>will be used to store loan and EMI related information</description>
    <fields>
        <fullName>DSA_Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DSA/Connector</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Accounts</relationshipLabel>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disbursal_Amount__c</fullName>
        <label>Disbursal Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ROI__c</fullName>
        <label>ROI</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Loan Account</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/SalesIncentiveUCV_Batch_Test.cls
@isTest
public class SalesIncentiveUCV_Batch_Test {
    public static testmethod void testUCVDirect(){
        
        id RecordType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Contact c = TestDataFactory.CreateApplicant(RecordType,'Lead - UCV',system.today(),5000000,17);
        Loan_Account__c la2 =TestDataFactory.CreatLoanAccount(c.id,false);
         la2.Disbursal_Amount__c=6100000;
         la2.ROI__c=17;
         insert la2;
         UserRole ur = new UserRole(Name ='Sales Manager-UCV ');
        
        Profile pf = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
       
       
        
        User u = new User(Alias = 'standt', Email='demouser1@damcogroup.com',
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                           LocaleSidKey='en_US', ProfileId = pf.Id, 
                           TimeZoneSidKey='America/Los_Angeles', UserName='demouser1@damcogroup.com.ambit',
                           UserRoleId = ur.id);
        insert u;
         system.debug('user role-->'+u.UserRoleId);
        System.runAs(u){
          Test.startTest();
        SalesIncentiveUCV_Batch obj = new SalesIncentiveUCV_Batch();
        DataBase.executeBatch(obj); 
        Test.stopTest();    
        }
          
    }
    
    public static testmethod void testUCVNonDirect(){
        id AccRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        // create a Dsa account
        Account acc=TestDataFactory.CreateAccount(AccRecordType);
        id RecordType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        // create Applicant
        Contact c = TestDataFactory.CreateApplicant(RecordType,'Lead - UCV',system.today(),5000000,17);
        // create Loan account
        Loan_Account__c la2 =TestDataFactory.CreatLoanAccount(c.id,false);
         la2.Disbursal_Amount__c=6100000;
         la2.ROI__c=17;
         la2.DSA_Connector__c=acc.Id;
         insert la2;
        Profile pf = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
       
        UserRole ur = new UserRole(Name ='Sales Manager-UCV ');
        
        User u = new User(Alias = 'standt', Email='demouser1@damcogroup.com',
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                           LocaleSidKey='en_US', ProfileId = pf.Id, 
                           TimeZoneSidKey='America/Los_Angeles', UserName='demouser1@damcogroup.com.ambit',
                           UserRoleId = ur.id);
        insert u;
        
        System.runAs(u){
            Test.startTest();
        SalesIncentiveUCV_Batch obj = new SalesIncentiveUCV_Batch();
        DataBase.executeBatch(obj); 
        Test.stopTest();  
            
        }
          
    }
   
}