unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DSA_Connector__c</fullName>
        <label>DSA / Connector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DSA</fullName>
                </value>
                <value>
                    <fullName>Connector</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Adherence_to_Ambit_Values_Target__c</fullName>
        <label>Adherence to Ambit Values Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Adherence_to_Ambit_Values__c</fullName>
        <label>Adherence To Ambit Values</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <formula>User__r.Branch__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Branch</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cases_Disbursed_in_last_3_days_Target__c</fullName>
        <defaultValue>&apos;Not more than 10%&apos;</defaultValue>
        <label>Cases Disbursed in last 3 days Target(%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Communication_and_email_skillset_Target__c</fullName>
        <label>Communication and email skillset Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Communication_and_email_skillset__c</fullName>
        <label>Communication and Email Skill Set</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Generation_Target__c</fullName>
        <label>Lead Generation Target</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_Lead_Conversation_Ratio__c</fullName>
        <label>Meeting/Lead Conversation Ratio Ach (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>TEXT( User__r.Product__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <label>Achievement</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Achievement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <label>Applicant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Co-Applicant</fullName>
                </value>
                <value>
                    <fullName>Guarantor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Branch)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lead - VYAPAR (SECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UDYAM (UNSECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UCV</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Vyapar</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Udyam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Loan_Account__c.object
<CustomObject>
    <description>will be used to store loan and EMI related information</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Loan Accounts (Lead)</relationshipLabel>
        <relationshipName>Loan_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DPD__c</fullName>
        <label>DPD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DSA_Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DSA/Connector</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Accounts</relationshipLabel>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disbursal_Amount__c</fullName>
        <label>Disbursal Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Disbursal_Date__c</fullName>
        <label>Disbursal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LOAN_STATUS__c</fullName>
        <label>LOAN STATUS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Loan Account</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Targets__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active </label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Adherence_to_Ambit_Values__c</fullName>
        <defaultValue>&apos;Open rating to be available from 0 to 5&apos;</defaultValue>
        <label>Adherence to Ambit Values</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval_Ratio__c</fullName>
        <label>Approval Ratio (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cases_Disbursed_in_last_3_days__c</fullName>
        <defaultValue>&apos;Not more than 10%&apos;</defaultValue>
        <label>Cases Disbursed in last 3 days (%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Communication_and_email_skillset__c</fullName>
        <defaultValue>&apos;Open rating to be available from 0 to 5&apos;</defaultValue>
        <label>Communication and email skillset</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Direct_Biz_Sourced__c</fullName>
        <label>Direct Biz Sourced (%)</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FTR__c</fullName>
        <label>FTR (%)</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>IRR__c</fullName>
        <label>IRR (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Insurance_Penetration__c</fullName>
        <label>Insurance Penetration (%)</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Lead_Generation_Target__c</fullName>
        <label>Lead Generation Target</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_Lead_Conversation_Ratio__c</fullName>
        <label>Meeting/Lead Conversation Ratio (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Meeting_Targets__c</fullName>
        <label>Meetings Target</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NPA__c</fullName>
        <defaultValue>&apos;As per Org Norms&apos;</defaultValue>
        <label>NPA (%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_PF__c</fullName>
        <label>Net PF(%)</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>No_of_Files_Logged_In_No__c</fullName>
        <label>No of Files Logged In (No)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Files_Logged_In__c</fullName>
        <label>No of Files Logged In (Value)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Units_Disbursed__c</fullName>
        <label>No.of Units Disbursed</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OTC_PDD_above_norms__c</fullName>
        <defaultValue>&apos;Nil OTC and PDD pending for more than 7 days and 90 days respectively&apos;</defaultValue>
        <label>OTC/PDD above norms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_conduct_and_Cross_function_deali__c</fullName>
        <defaultValue>&apos;Open rating to be available from 0 to 5&apos;</defaultValue>
        <label>Overallconduct/Crossfunction dealings</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_grooming_attendance_discipline__c</fullName>
        <defaultValue>&apos;Open rating to be available from 0 to 5&apos;</defaultValue>
        <label>Overall-grooming/attendance/discipline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query_TAT_Resolution__c</fullName>
        <defaultValue>&apos;80% cases to be resolved in T+4 days&apos;</defaultValue>
        <label>Query TAT Resolution (%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Targets2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date </label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume (In Cr)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Target</label>
    <nameField>
        <label>Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTC_Range_Max_In_Lakhs__c</fullName>
        <label>CTC Range Max (In Lakhs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CTC_Range_Min_In_Lakhs__c</fullName>
        <label>CTC Range Min (In Lakhs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Secured</fullName>
                </value>
                <value>
                    <fullName>Unsecured</fullName>
                </value>
                <value>
                    <fullName>UCV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    
    public static User CreateUser(){
         Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        UserRole ur = [select id,Name FROM UserRole WHERE Name ='Sales Manager-UCV'];
        //creating user
        User u = new User(Alias = 'standt', Email='demouser1@damcogroup.com',
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                           LocaleSidKey='en_US', ProfileId = p.Id, 
                           TimeZoneSidKey='America/Los_Angeles', UserName='demouser1@damcogroup.com.ambit',Branch__c='Delhi',
                          CTC_Range_Max_In_Lakhs__c = 14,CTC_Range_Min_In_Lakhs__c = 12, UserRoleId = ur.id);
        

        
            insert u;
            return u;
    }
    public static User CreateUser2(){
         Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        UserRole ur = [select id,Name FROM UserRole WHERE Name ='RSM / Zonal Sales Manager'];
        //creating user
        User u = new User(Alias = 'standt', Email='demouser2@damcogroup.com',
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                           LocaleSidKey='en_US', ProfileId = p.Id, 
                           TimeZoneSidKey='America/Los_Angeles',UserRoleId = ur.id, UserName='demouser2@damcogroup.com.ambit');
        insert u;
        return u;
    }
    public static Account CreateAccount(id recordTypeId,string dsaorconnector){
        Account acc = new Account();
        acc.RecordTypeId = recordTypeId;
        acc.FirstName = 'Test';
        acc.LastName = 'App';
        acc.Email__c = 'testmail@abc.com';
        acc.Phone = '6876875888';
        acc.DSA_Connector__c=dsaorconnector;
        insert acc;
        return acc;
    }
    public static Account CreateAaccountDsa(id recordTypeId,Boolean doInsert){
        Account acc = new Account();
        acc.RecordTypeId = recordTypeId;
        acc.FirstName = 'Test';
        acc.LastName = 'App';
        acc.Email__c = 'testmail@abc.com';
        acc.Phone = '6876875888';
        acc.DSA_Connector__c='DSA';
        if(doInsert)
        {
            insert acc;
        }
        return acc;
    }
    public static Contact CreateApplicant(id recordTypeId, String prouctType){
        Contact app = new Contact();
        app.RecordTypeId = recordTypeId;
        app.FirstName = 'Test';
        app.LastName = 'App';
        app.Email = 'testmail@abc.com';
        app.Phone = '6876875888';
        app.Product__c = prouctType;
        
        insert app;
        return app;
    }
    
    public static Contact CreateApplicantbulk(id recordTypeId, String prouctType,Boolean doInsert){
        Contact app = new Contact();
        app.RecordTypeId = recordTypeId;
        app.FirstName = 'Test';
        app.LastName = 'App';
        app.Email = 'testmail@abc.com';
        app.Phone = '6876875888';
        app.Product__c = prouctType;
        app.Applicant_Type__c='Applicant';
        if(doInsert)
        {
            insert app;
        }
        return app;
    }
    
    Public static Loan_Account__c CreatLoanAccount(id contact ,Boolean doInsert){
        Loan_Account__c la = new Loan_Account__c();
        la.Applicant__c = contact;
        la.DPD__c=0;
        la.Disbursal_Amount__c=500000;
        la.Disbursal_Date__c=system.today();
        la.LOAN_STATUS__c='Disbursed';
        if(doInsert)
        {
            insert la;
        }
        
        return la;
    }
    
    Public static Targets__c CreatTargets(Boolean doInsert ,id User ){
        
      Targets__c ta= new Targets__c();
        ta.Name='Test Traget';
        ta.Active__c=true;
        ta.Meeting_Targets__c=5;
        ta.Meeting_Lead_Conversation_Ratio__c=2;
        ta.Lead_Generation_Target__c=5;
        ta.No_of_Files_Logged_In_No__c=4;
        ta.No_of_Files_Logged_In__c=3;
        ta.No_of_Units_Disbursed__c=3;
        ta.Volume__c=12000.00;
        ta.IRR__c=3;
        ta.Net_PF__c=2;
        ta.Insurance_Penetration__c=2;
        ta.Direct_Biz_Sourced__c=3;
        ta.FTR__c=1;
        ta.Query_TAT_Resolution__c='test query';
        ta.Approval_Ratio__c=2;
        ta.OTC_PDD_above_norms__c='no';
        ta.Cases_Disbursed_in_last_3_days__c='no';
        ta.NPA__c='testnaps';
        ta.Salesperson__c=User;
        ta.Adherence_to_Ambit_Values__c='test ambit';
        ta.Communication_and_email_skillset__c='test com';
        ta.Overall_conduct_and_Cross_function_deali__c='test overall';
        ta.Overall_grooming_attendance_discipline__c='test'; 
        ta.Start_Date__c=date.newinstance(2021,4,1);
        ta.End_Date__c=system.today();
        if(doInsert){
             insert ta;
        }
         return ta;
        
    }
      Public static Achievement__c createAchievement(Boolean doInsert ,id User ){
        
      Achievement__c ta= new Achievement__c(Adherence_to_Ambit_Values_Target__c='Open rating to be available from 0 to 5',
                                            Cases_Disbursed_in_last_3_days_Target__c='Not more than 10%',Communication_and_email_skillset_Target__c='Open rating to be available from 0 to 5',
                                            Duration_Achievement__c='Monthly',Insurance_Penetration_Target__c=3,IRR_Target__c=15,Lead_Generation_Target__c=5,
                                            Meeting_Achievement__c=3,Meeting_Lead_Conversion_Ratio_Target__c=50,Meetings_Target__c=5,
                                    		Month__c='November',Net_PF_Target__c=5,No_of_Files_Logged_In_Target__c=5,No_of_Units_Disbursed_Target__c=5,
                                    		NPA_Achieved__c=5.5555,NPA_Target__c='As per Org Norms',
                                    		OTC_PDD_above_norms_Target__c='Nil OTC and PDD pending for more than 7 days and 90 days respectively',
                                            Overall_grooming_attendance_dis_Target__c='Open rating to be available from 0 to 5',
                                            Overallconduct_Crossfunction_deal_Target__c='Open rating to be available from 0 to 5',Query_TAT_Resolution_Target__c='80% cases to be resolved in T+4 days',
                                            User__c=User,Value_of_Files_Logged_In_Targets__c=1500000,Value_Target__c=50,Year__c='2021');
      
        if(doInsert){
             insert ta;
        }
         return ta;
        
    }
    Public static Sales_Plan__c createSales_Plan(Boolean doInsert ,id User ){
        
      Sales_Plan__c ta= new Sales_Plan__c(Month__c='November',No_of_disbursement__c=1,No_Of_Lead__c=2,
                                            No_of_login_value__c=5000000,No_of_Logins__c=1,No_of_Meetings__c=2,Plan_Type__c='Weekly',
                                            volume_of_disbursement__c=3000000,Week__c='1',Year__c='2021');
      
        if(doInsert){
             insert ta;
        }
         return ta;
        
    }
    
}