unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Agent_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Branch_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch Manager Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DSA_Connector__c</fullName>
        <label>DSA / Connector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DSA</fullName>
                </value>
                <value>
                    <fullName>Connector</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Branch</fullName>
        <active>true</active>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Branch_Manager__c</fullName>
        <formula>Branch__r.Branch_Manager__r.FirstName + &apos;&apos;+
Branch__r.Branch_Manager__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Branch Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lead - VYAPAR (SECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UDYAM (UNSECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UCV</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Vyapar</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Udyam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open - Lead</fullName>
                </value>
                <value>
                    <fullName>Appointment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Appointment Re-schdeduled</fullName>
                </value>
                <value>
                    <fullName>CIBIL Updated</fullName>
                </value>
                <value>
                    <fullName>Under Qualification process</fullName>
                </value>
                <value>
                    <fullName>Documentation in process</fullName>
                </value>
                <value>
                    <fullName>Sales Team Qualified</fullName>
                </value>
                <value>
                    <fullName>SM Queue</fullName>
                </value>
                <value>
                    <fullName>Sales Co-ordinator Queue</fullName>
                </value>
                <value>
                    <fullName>BM Queue</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Not Contactable</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>Document Processing</fullName>
                    <isActive>false</isActive>
                    <label>Document Processing</label>
                </value>
                <value>
                    <fullName>Document Verification</fullName>
                    <isActive>false</isActive>
                    <label>Document Verification</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                    <isActive>false</isActive>
                    <label>Prospecting</label>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                    <isActive>false</isActive>
                    <label>Qualification</label>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <isActive>false</isActive>
                    <label>Qualified</label>
                </value>
                <value>
                    <fullName>Quote Sent</fullName>
                    <isActive>false</isActive>
                    <label>Quote Sent</label>
                </value>
                <value>
                    <fullName>Underwriting</fullName>
                    <isActive>false</isActive>
                    <label>Underwriting</label>
                </value>
                <value>
                    <fullName>Working</fullName>
                    <isActive>false</isActive>
                    <label>Working</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Loan_Account__c.object
<CustomObject>
    <description>will be used to store loan and EMI related information</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Loan Accounts (Lead)</relationshipLabel>
        <relationshipName>Loan_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DSA_Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DSA/Connector</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Accounts</relationshipLabel>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LOAN_STATUS__c</fullName>
        <label>LOAN STATUS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for loan if any is Pending or loan is fully paid</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applied</fullName>
                    <default>true</default>
                    <label>Applied</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Disbursed</fullName>
                </value>
                <value>
                    <fullName>EMI Scheduled</fullName>
                </value>
                <value>
                    <fullName>Pending Closure</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loan Account</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Meeting__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DSA_Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DSA/Connector</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Account</label>
        <referenceTo>Loan_Account__c</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Re-Scheduled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Meeting</label>
    <nameField>
        <displayFormat>MEET-{0000}</displayFormat>
        <label>Meeting #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Sales_Incentive__c.object
<CustomObject>
    <fields>
        <fullName>DSA_Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DSA/Connector</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Incentives</relationshipLabel>
        <relationshipName>Sales_Incentives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesperson_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesperson/Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Sales Incentives</relationshipLabel>
        <relationshipName>Sales_Incentives</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Incentive</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Incentives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Secured</fullName>
                </value>
                <value>
                    <fullName>Unsecured</fullName>
                </value>
                <value>
                    <fullName>UCV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/ShareRecordsToManagers_Test.cls
@isTest
public class ShareRecordsToManagers_Test {
    public static testmethod void test1(){
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Sales Profile'];
        // inserting role in data setup
        UserRole SalesOfficer = new UserRole(Name ='Sales Officer-Rest of India');
        insert SalesOfficer;
        UserRole SalesManager = new UserRole(Name ='Sales Manager-Rest of India');
        insert SalesManager;
        UserRole BranchManager = new UserRole(Name ='Branch Manager-Rest of India');
        insert BranchManager;
        
        // inserting Users in data setup
        User BManager = new User(Alias = 'standt2', Email='Ambitstandarduser2@testorg.com', 
                                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                 LocaleSidKey='en_US', ProfileId = p.Id,UserRoleId=BranchManager.id, 
                                 TimeZoneSidKey='America/Los_Angeles', UserName='Ambitstandarduser2@testorg.com');
        insert BManager;
        
        User SManager = new User(Alias ='standt1', Email='Ambitstandarduser1@testorg.com', 
                                 EmailEncodingKey='UTF-8', LastName='Testing13', LanguageLocaleKey='en_US', 
                                 LocaleSidKey='en_US', ProfileId = p.Id,UserRoleId=SalesManager.id,managerID=BManager.id, 
                                 TimeZoneSidKey='America/Los_Angeles', UserName='Ambitstandarduser13@aol.com');
        insert SManager;
        
        User sales = new User(Alias = 'standt', Email='Ambitstandarduser@testorg.com', 
                              EmailEncodingKey='UTF-8', LastName='Testing2', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id,UserRoleId=SalesOfficer.id,managerID=SManager.id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='Ambitstandarduser@ask.com');
        insert sales;
        
        system.runAs(sales){
            
            Contact c = new Contact();
            c.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
            c.FirstName = 'Test';
            c.LastName = 'Name';
            c.Email = 'test@abc.com';
            c.Phone = '86559944';
            c.Product__c = 'Lead - VYAPAR (SECURED LOAN)';
            insert c;
            
            Loan_Account__c la = new Loan_Account__c();
            la.Applicant__c = c.id;
            la.LOAN_STATUS__c='Pending';
            la.OwnerId=sales.Id;
            insert la;
            
            Meeting__c meet = new Meeting__c ();
            meet.Status__c = 'Scheduled';
            meet.Loan_Account__c = la.id;
            insert meet;
            
            Account branch = new Account();
            branch.name = 'Allahabad';
            branch.Branch_Manager__c = SManager.id;
            branch.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Branch').getRecordTypeId();
            insert branch;
            
            Account branch2 = new Account();
            branch2.name = 'CORPORATE';
            branch2.Branch_Manager__c = SManager.id;
            branch2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Branch').getRecordTypeId();
            insert branch2;
            
            Account  dsa= new Account();
            dsa.Agent_Branch__c = branch.id;
            dsa.name = 'test dsa';
            insert dsa;
            
            Account  dsa2= new Account();
            dsa2.Agent_Branch__c = branch2.id;
            dsa2.name = 'test dsa2';
            insert dsa2;
            
            Sales_Incentive__c si = new Sales_Incentive__c();
            si.DSA_Connector__c = dsa.id;
            insert si;
            
            Sales_Incentive__c si2 = new Sales_Incentive__c();
            si2.Salesperson_Agent__c = SManager.id;
            insert si2;
            
            Sales_Incentive__c si3 = new Sales_Incentive__c();
            si3.DSA_Connector__c = dsa2.id;
            insert si3;
            
        }
        
    }
    
}