unpackaged/objects/Achievement__c.object
<CustomObject>
    <fields>
        <fullName>IRR_Achieved__c</fullName>
        <label>IRR Achieved (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Lead_Generation_Achieved__c</fullName>
        <label>Lead Generation Achieved</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_Achievement__c</fullName>
        <label>Meeting Achievement</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Net_PF_Achieved__c</fullName>
        <label>Net PF Achieved (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>No_of_Files_Logged_In_Achieved__c</fullName>
        <label>No. of Files Logged In Achieved</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Achievement</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Achievement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/Achievement_Trigger_Test.cls
@istest
public class Achievement_Trigger_Test {
    public static testmethod void test1(){
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        //creating user
        User u = new User(Alias = 'standt', Email='demouser1@damcogroup.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='demouser1@damcogroup.com.ambit');
        insert u;
        Achievement__c ac= new Achievement__c();
        ac.Meeting_Achievement__c=10;
        ac.Lead_Generation_Achieved__c=5;
        ac.No_of_Files_Logged_In_Achieved__c=4;
        ac.User__c=u.id;
        
        insert ac;
        
        ac.Net_PF_Achieved__c=1.2;
        ac.IRR_Achieved__c=17;
        
        update ac;
        
    }
}