unpackaged/objects/Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>High_Level_Work_Plan__c</fullName>
        <label>High Level Work Plan</label>
        <type>TextArea</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <displayFormat>ATT-{0000}</displayFormat>
        <label>Attendance #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/Attendance_Trigger_test.cls
@isTest
public class Attendance_Trigger_test {
  public static testmethod void test1(){
      
      Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        //creating user
        User u = new User(Alias = 'standt', Email='demouser1@damcogroup.com',
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                           LocaleSidKey='en_US', ProfileId = p.Id, 
                           TimeZoneSidKey='America/Los_Angeles', UserName='demouser1@damcogroup.com.ambit');
        insert u;
      
      Attendance__c atten = new Attendance__c();
      atten.Date__c=system.today();
      atten.High_Level_Work_Plan__c='test plan';
      atten.OwnerId=u.id;
       insert atten;
      
      
  }
}