unpackaged/objects/Batch_Log__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Batch Logs</relationshipLabel>
        <relationshipName>Batch_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Batch_Id__c</fullName>
        <label>Batch_Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_details__c</fullName>
        <label>Error details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MessageViewed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MessageViewed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Batch Log</label>
    <nameField>
        <label>Batch Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/RefreshBatchStatus.cls
public class RefreshBatchStatus {
    @AuraEnabled
    public static Batch_Log__c getAPIError(string recordId){
        system.debug('recordId '+recordId);
        Batch_Log__c obj=new Batch_Log__c();
        Batch_Log__c[] groupedResults = [SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, LastViewedDate, LastReferencedDate, Batch_Id__c, Status__c, Message__c, Error_details__c, Applicant__c, MessageViewed__c FROM Batch_Log__c where Applicant__c=:recordId and MessageViewed__c=false order by createddate desc limit 1];
       if(!groupedResults.isEmpty())
       {
           obj=groupedResults[0];
           obj.MessageViewed__c=true;
           update obj;
       }
        
        return  obj ;
    }
    
}