unpackaged/objects/Collection_Task__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Date__c</fullName>
        <label>Assigned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Collection Tasks</relationshipLabel>
        <relationshipName>Collection_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EMI_Overdue_Amount__c</fullName>
        <label>EMI Overdue Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Initial_Total_Amount_To_Be_Recovered__c</fullName>
        <label>Initial Total Amount To Be Recovered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Account</label>
        <referenceTo>Loan_Account__c</referenceTo>
        <relationshipLabel>Collection Tasks</relationshipLabel>
        <relationshipName>Collection_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Other_Overdue_Amount__c</fullName>
        <label>Other Overdue Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete - Overdue amount Pending</fullName>
                </value>
                <value>
                    <fullName>Complete - Fully Recovered</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Collection Task</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Collection #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Task</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open - Lead</fullName>
                </value>
                <value>
                    <fullName>Appointment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Appointment Re-schdeduled</fullName>
                </value>
                <value>
                    <fullName>CIBIL Updated</fullName>
                </value>
                <value>
                    <fullName>Under Qualification process</fullName>
                </value>
                <value>
                    <fullName>Documentation in process</fullName>
                </value>
                <value>
                    <fullName>Sales Team Qualified</fullName>
                </value>
                <value>
                    <fullName>SM Queue</fullName>
                </value>
                <value>
                    <fullName>Sales Co-ordinator Queue</fullName>
                </value>
                <value>
                    <fullName>BM Queue</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Not Contactable</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>Document Processing</fullName>
                    <isActive>false</isActive>
                    <label>Document Processing</label>
                </value>
                <value>
                    <fullName>Document Verification</fullName>
                    <isActive>false</isActive>
                    <label>Document Verification</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                    <isActive>false</isActive>
                    <label>Prospecting</label>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                    <isActive>false</isActive>
                    <label>Qualification</label>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <isActive>false</isActive>
                    <label>Qualified</label>
                </value>
                <value>
                    <fullName>Quote Sent</fullName>
                    <isActive>false</isActive>
                    <label>Quote Sent</label>
                </value>
                <value>
                    <fullName>Underwriting</fullName>
                    <isActive>false</isActive>
                    <label>Underwriting</label>
                </value>
                <value>
                    <fullName>Working</fullName>
                    <isActive>false</isActive>
                    <label>Working</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Loan_Account__c.object
<CustomObject>
    <description>will be used to store loan and EMI related information</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Loan Accounts (Lead)</relationshipLabel>
        <relationshipName>Loan_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DPD__c</fullName>
        <label>DPD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EMI_Overdue_Amount__c</fullName>
        <label>EMI Overdue Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LOAN_STATUS__c</fullName>
        <label>LOAN STATUS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Overdue_Amount__c</fullName>
        <label>Other Overdue Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for loan if any is Pending or loan is fully paid</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applied</fullName>
                    <default>true</default>
                    <label>Applied</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Disbursed</fullName>
                </value>
                <value>
                    <fullName>EMI Scheduled</fullName>
                </value>
                <value>
                    <fullName>Pending Closure</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loan Account</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/LoanAccountTriggerHandler.cls
public class LoanAccountTriggerHandler {
    
    public static void CreateCollectionTask(Set<Id> LoanAccIdSet,Map<Id,Loan_Account__c>OldMap,Map<Id,Loan_Account__c>NewMap){
        List<Collection_Task__c> tasksList = new List<Collection_Task__c>();
        List<Collection_Task__c> updatetasksList = new List<Collection_Task__c>();
        List<Loan_Account__c> LoanAccList = [SELECT id, Applicant__c,Applicant__r.OwnerId,DPD__c,EMI_Overdue_Amount__c,LOAN_STATUS__c,Other_Overdue_Amount__c FROM Loan_Account__c WHERE id=:LoanAccIdSet]; 
        list<Collection_Task__c>collectionlistcompleted=[SELECT id,Loan_Account__c,Name,Status__c from Collection_Task__c where Loan_Account__c=:LoanAccIdSet and (Status__c=:'Complete - Fully Recovered' or Status__c=:'Complete - Overdue amount Pending')];
        list<Collection_Task__c>collectionlistpending=[SELECT id,Loan_Account__c,Name,Status__c from Collection_Task__c where Loan_Account__c=:LoanAccIdSet and Status__c=:'Pending'];
        Group groupDetail =[select id, Name from Group where Type = 'Queue'];
        Integer AmountDpd;
        Integer Initaltoatlamount;
        if(LoanAccList != null && LoanAccList.size()>0 ){
            for(Loan_Account__c la:LoanAccList){
                if(la.DPD__c!=Oldmap.get(la.Id).DPD__c || la.EMI_Overdue_Amount__c!=Oldmap.get(la.Id).EMI_Overdue_Amount__c || la.Other_Overdue_Amount__c!=Oldmap.get(la.Id).Other_Overdue_Amount__c){
                    if(AmountDpd==null  && Initaltoatlamount==null && la.EMI_Overdue_Amount__c!=null && la.DPD__c!=null && (la.Other_Overdue_Amount__c!=null ||la.Other_Overdue_Amount__c==null) && la.LOAN_STATUS__c=='Disbursed'){
                        AmountDpd= Integer.valueOf(la.DPD__c);
                        if(la.EMI_Overdue_Amount__c!=null && la.Other_Overdue_Amount__c!=null ){
                            Initaltoatlamount= Integer.valueOf(la.EMI_Overdue_Amount__c)+Integer.valueOf(la.Other_Overdue_Amount__c);
                        }else if(la.Other_Overdue_Amount__c==null && la.EMI_Overdue_Amount__c!=null){
                            Initaltoatlamount= Integer.valueOf(la.EMI_Overdue_Amount__c);
                        }
                    }  
                }
                // if any pending record created on collection task already 
                if(!collectionlistpending.isEmpty()){
                    for(Collection_Task__c coll:collectionlistpending){
                        if(coll.Status__c=='Pending'){
                            coll.Loan_Account__c = la.id;
                            coll.Initial_Total_Amount_To_Be_Recovered__c=Initaltoatlamount;
                            coll.EMI_Overdue_Amount__c=la.EMI_Overdue_Amount__c;
                            if(la.Other_Overdue_Amount__c!=null){
                                coll.Other_Overdue_Amount__c=la.Other_Overdue_Amount__c; 
                            }
                            else if(la.Other_Overdue_Amount__c==null){
                                coll.Other_Overdue_Amount__c=0;
                            }
                            
                            updatetasksList.add(coll);
                        }
                        
                    }
                }
                //if collection task create on loan with all the value as completed
                if(!collectionlistcompleted.isEmpty() && collectionlistpending.isEmpty()){
                    if(la.LOAN_STATUS__c=='Disbursed' && AmountDpd > 0){
                        Collection_Task__c ct = new Collection_Task__c();
                        ct.Loan_Account__c = la.id;
                        if(la.Applicant__c != null)
                            ct.Customer__c = la.Applicant__c;
                        ct.Status__c = 'Pending';
                        ct.Assigned_Date__c = system.today();
                        ct.Initial_Total_Amount_To_Be_Recovered__c=Initaltoatlamount;
                        ct.EMI_Overdue_Amount__c=la.EMI_Overdue_Amount__c;
                        if(la.Other_Overdue_Amount__c!=null){
                            ct.Other_Overdue_Amount__c=la.Other_Overdue_Amount__c; 
                        }
                        else if(la.Other_Overdue_Amount__c==null){
                            ct.Other_Overdue_Amount__c=0;
                        }
                        
                        tasksList.add(ct);
                    }   
                } 
                
                //no collection task is created yet for loan account
                
                if(collectionlistcompleted.isEmpty() && collectionlistpending.isEmpty()){
                    if(la.LOAN_STATUS__c=='Disbursed' && AmountDpd > 0){
                        Collection_Task__c ct = new Collection_Task__c();
                        ct.Loan_Account__c = la.id;
                        if(la.Applicant__c != null)
                            ct.Customer__c = la.Applicant__c;
                        ct.Status__c = 'Pending';
                        ct.Assigned_Date__c = system.today();
                        ct.Initial_Total_Amount_To_Be_Recovered__c=Initaltoatlamount;
                        ct.EMI_Overdue_Amount__c=la.EMI_Overdue_Amount__c;
                        ct.OwnerId=groupDetail.id;
                        if(la.Other_Overdue_Amount__c!=null){
                            ct.Other_Overdue_Amount__c=la.Other_Overdue_Amount__c; 
                        }
                        else if(la.Other_Overdue_Amount__c==null){
                            ct.Other_Overdue_Amount__c=0;
                        }
                        
                        tasksList.add(ct);
                    } 
                }
                
            }
            if(tasksList != null && tasksList.size()>0){
                try{
                    insert tasksList;
                }
                catch(exception e){
                    system.debug('error: '+e.getMessage());
                }
            }
            if(updatetasksList != null && updatetasksList.size()>0){
                try{
                    upsert updatetasksList;
                }
                catch(exception e){
                    system.debug('error: '+e.getMessage());
                }
            }
        }
        
    }
    
}