unpackaged/objects/Collection_Task__c.object
<CustomObject>
    <fields>
        <fullName>EMI_Overdue_Amount__c</fullName>
        <label>EMI Overdue Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Account</label>
        <referenceTo>Loan_Account__c</referenceTo>
        <relationshipLabel>Collection Tasks</relationshipLabel>
        <relationshipName>Collection_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Other_Overdue_Amount__c</fullName>
        <label>Other Overdue Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete - Overdue amount Pending</fullName>
                </value>
                <value>
                    <fullName>Complete - Fully Recovered</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Collection Task</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Collection #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Task</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lead - VYAPAR (SECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UDYAM (UNSECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UCV</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Vyapar</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Udyam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open - Lead</fullName>
                </value>
                <value>
                    <fullName>Appointment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Appointment Re-schdeduled</fullName>
                </value>
                <value>
                    <fullName>CIBIL Updated</fullName>
                </value>
                <value>
                    <fullName>Under Qualification process</fullName>
                </value>
                <value>
                    <fullName>Documentation in process</fullName>
                </value>
                <value>
                    <fullName>Sales Team Qualified</fullName>
                </value>
                <value>
                    <fullName>SM Queue</fullName>
                </value>
                <value>
                    <fullName>Sales Co-ordinator Queue</fullName>
                </value>
                <value>
                    <fullName>BM Queue</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Not Contactable</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>Document Processing</fullName>
                    <isActive>false</isActive>
                    <label>Document Processing</label>
                </value>
                <value>
                    <fullName>Document Verification</fullName>
                    <isActive>false</isActive>
                    <label>Document Verification</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                    <isActive>false</isActive>
                    <label>Prospecting</label>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                    <isActive>false</isActive>
                    <label>Qualification</label>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <isActive>false</isActive>
                    <label>Qualified</label>
                </value>
                <value>
                    <fullName>Quote Sent</fullName>
                    <isActive>false</isActive>
                    <label>Quote Sent</label>
                </value>
                <value>
                    <fullName>Underwriting</fullName>
                    <isActive>false</isActive>
                    <label>Underwriting</label>
                </value>
                <value>
                    <fullName>Working</fullName>
                    <isActive>false</isActive>
                    <label>Working</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Loan_Account__c.object
<CustomObject>
    <description>will be used to store loan and EMI related information</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Loan Accounts (Lead)</relationshipLabel>
        <relationshipName>Loan_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DPD__c</fullName>
        <label>DPD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EMI_Overdue_Amount__c</fullName>
        <label>EMI Overdue Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LOAN_STATUS__c</fullName>
        <label>LOAN STATUS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Overdue_Amount__c</fullName>
        <label>Other Overdue Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for loan if any is Pending or loan is fully paid</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applied</fullName>
                    <default>true</default>
                    <label>Applied</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Disbursed</fullName>
                </value>
                <value>
                    <fullName>EMI Scheduled</fullName>
                </value>
                <value>
                    <fullName>Pending Closure</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loan Account</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/LoanAccountTriggerHandler_Test.cls
@isTest
public class LoanAccountTriggerHandler_Test {
    public static testmethod void test1(){
        Contact c = new Contact();
        c.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        c.FirstName = 'Test';
        c.LastName = 'Name';
        c.Email = 'test@abc.com';
        c.Phone = '86559944';
        c.Product__c = 'Lead - VYAPAR (SECURED LOAN)';
        insert c;
        Loan_Account__c la = new Loan_Account__c();
        la.Applicant__c = c.id;
        la.DPD__c=0;
        la.EMI_Overdue_Amount__c=1500;
        la.Other_Overdue_Amount__c=500;
        la.LOAN_STATUS__c='Pending';
        insert la;
        
        la.LOAN_STATUS__c='Disbursed';
        la.DPD__c=2;
        update la; 
         
        
        
        list<Collection_Task__c>collectionlistpending=[SELECT id,Loan_Account__c,Name,Status__c from Collection_Task__c where Loan_Account__c=:la.id and Status__c=:'Pending'];  
        la.DPD__c=24;
        la.EMI_Overdue_Amount__c=1200;
        la.Other_Overdue_Amount__c=300;
        update la;
        
        Collection_Task__c coll = new Collection_Task__c();
        for(Collection_Task__c ca: collectionlistpending){
            ca.Status__c='Complete - Fully Recovered';
            ca.Loan_Account__c=la.id;
             update ca;
            
            
        }   
    }
    
      public static testmethod void test2(){
        Contact c1 = new Contact();
        c1.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        c1.FirstName = 'Test';
        c1.LastName = 'Name';
        c1.Email = 'test@abc.com';
        c1.Phone = '86559944';
        c1.Product__c = 'Lead - VYAPAR (SECURED LOAN)';
        insert c1;
        Loan_Account__c la1 = new Loan_Account__c();
        la1.Applicant__c = c1.id;
        la1.DPD__c=0;
        la1.EMI_Overdue_Amount__c=1500;
        la1.Other_Overdue_Amount__c=500;
        la1.LOAN_STATUS__c='Pending';
        insert la1;
        
        la1.LOAN_STATUS__c='Disbursed';
        la1.DPD__c=2;
        update la1; 
    
          Collection_Task__c collectionlistpending=[SELECT id,Loan_Account__c,Name,Status__c from Collection_Task__c where Loan_Account__c=:la1.id and Status__c=:'Pending' ];
           Collection_Task__c coll = new Collection_Task__c();
          coll.id= collectionlistpending.id; 
          coll.Status__c='Complete - Fully Recovered';
           coll.Loan_Account__c=la1.id;
             update coll;
          
        list<Collection_Task__c>collectionlistcompleted=[SELECT id,Loan_Account__c,Name,Status__c from Collection_Task__c where Loan_Account__c=:la1.id and Status__c=:'Complete - Fully Recovered'];  
        la1.DPD__c=24;
        la1.EMI_Overdue_Amount__c=1200;
        la1.Other_Overdue_Amount__c=300;
        update la1;

        
       
            
            
        }
}