unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lead - VYAPAR (SECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UDYAM (UNSECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UCV</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Vyapar</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Udyam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Of_Interest__c</fullName>
        <label>Rate Of Interest</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Incentive_Setup__mdt.object
<CustomObject>
    <fields>
        <fullName>Eligible_Role__c</fullName>
        <label>Eligible Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Officer</fullName>
                    <default>true</default>
                    <label>Sales Officer</label>
                </value>
                <value>
                    <fullName>Sr Sales Officer</fullName>
                </value>
                <value>
                    <fullName>Sales Manager -Asst Manager</fullName>
                </value>
                <value>
                    <fullName>Sr Sales Manager-Deputy Manager</fullName>
                </value>
                <value>
                    <fullName>Sales Manager-UCV</fullName>
                </value>
                <value>
                    <fullName>Sales Officer-UCV</fullName>
                </value>
                <value>
                    <fullName>$User.Username</fullName>
                    <isActive>false</isActive>
                    <label>$User.Username</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Incentive__c</fullName>
        <label>Incentive %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Maximum_Amount__c</fullName>
        <label>Maximum Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Amount__c</fullName>
        <label>Minimum Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lead - VYAPAR (SECURED LOAN)</fullName>
                    <default>true</default>
                    <label>Lead - VYAPAR (SECURED LOAN)</label>
                </value>
                <value>
                    <fullName>Lead - UDYAM (UNSECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UCV</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Vyapar</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Udyam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <label>RecordType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Regular Incentive</fullName>
                    <default>true</default>
                    <label>Regular Incentive</label>
                </value>
                <value>
                    <fullName>Contest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sourcing__c</fullName>
        <label>Sourcing</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                    <default>true</default>
                    <label>Direct</label>
                </value>
                <value>
                    <fullName>Non Direct</fullName>
                </value>
                <value>
                    <fullName>DSA</fullName>
                </value>
                <value>
                    <fullName>Connector</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DSA</fullName>
                    <default>true</default>
                    <label>DSA</label>
                </value>
                <value>
                    <fullName>Salesperson</fullName>
                </value>
                <value>
                    <fullName>Connector</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WIRR_Higher_Limit__c</fullName>
        <label>WIRR Higher Limit %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>WIRR_Lower_Limit__c</fullName>
        <label>WIRR Lower Limit %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Incentive Setup</label>
    <pluralLabel>Incentive Setups</pluralLabel>
</CustomObject>

unpackaged/objects/Loan_Account__c.object
<CustomObject>
    <description>will be used to store loan and EMI related information</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Loan Accounts (Lead)</relationshipLabel>
        <relationshipName>Loan_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DSA_Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DSA/Connector</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Accounts</relationshipLabel>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disbursal_Amount__c</fullName>
        <label>Disbursal Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Disbursal_Date__c</fullName>
        <label>Disbursal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LOAN_STATUS__c</fullName>
        <label>LOAN STATUS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROI__c</fullName>
        <label>ROI</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>create_year__c</fullName>
        <formula>YEAR(DATEVALUE(CreatedDate))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>create year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Loan Account</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Sales_Incentive__c.object
<CustomObject>
    <fields>
        <fullName>DSA_Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DSA/Connector</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Incentives</relationshipLabel>
        <relationshipName>Sales_Incentives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incentive_Forecast_For_UCV__c</fullName>
        <label>Incentive Forecast For UCV</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Salesperson_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesperson/Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Sales Incentives</relationshipLabel>
        <relationshipName>Sales_Incentives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Sales Incentive</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Incentives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Secured</fullName>
                </value>
                <value>
                    <fullName>Unsecured</fullName>
                </value>
                <value>
                    <fullName>UCV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/Incentive_Forecast_UCV.cls
global class Incentive_Forecast_UCV implements Database.batchable<sObject>, Schedulable{
    global Database.QueryLocator start(Database.BatchableContext bc){
        Integer mnth = System.Today().MOnth();
        Integer yr = System.Today().Year();
        String Product = 'Lead - UCV';
        String loanstatus= 'Disbursed';
        String loanstatus1= 'Rejected';
        String query = 'Select Id,Disbursal_Amount__c,name,ROI__c,DSA_Connector__c,OwnerId,Applicant__r.Product__c,LOAN_STATUS__c,create_year__c,Applicant__r.Rate_Of_Interest__c,Applicant__r.Loan_Amount__c,Disbursal_Date__c From Loan_Account__c WHERE Applicant__r.Product__c=\''+String.escapeSingleQuotes(Product)+'\' and create_year__c=:yr and LOAN_STATUS__c!= \'' + loanstatus + '\' and LOAN_STATUS__c!= \'' + loanstatus1 + '\' ';
        system.debug(query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Loan_Account__c> scope){
        system.debug('List: '+scope);
        Map<Integer,String> monthMap = new Map<Integer,String>();
        monthMap.put(1, 'January'); monthMap.put(2, 'February');
        monthMap.put(3, 'March'); monthMap.put(4, 'April');
        monthMap.put(5, 'May'); monthMap.put(6, 'June');
        monthMap.put(7, 'july'); monthMap.put(8, 'August');
        monthMap.put(9, 'September'); monthMap.put(10, 'October');
        monthMap.put(11, 'November'); monthMap.put(12, 'December');
        
        Map<id,List<Loan_Account__c>> Agent_UCVLoanList_Map = new Map<id,List<Loan_Account__c>>();
        Map<id,Decimal> Agent_WIRR_UCV_DS_Map = new Map<id,Decimal>();
        Map<id,Decimal> Agent_WIRR_UCV_NDS_Map = new Map<id,Decimal>();
        Map<id,Decimal> Agent_TotalLoanAmt_UCV_Map = new Map<id,Decimal>();
        Map<id,Decimal> Agent_LoanAmt_UCV_DS_Map = new Map<id,Decimal>();
        Map<id,Decimal> Agent_LoanAmt_UCV_NDS_Map = new Map<id,Decimal>();
        
        for(Loan_Account__c Loan:scope){
            if(Loan.Disbursal_Amount__c==null|| Loan.Disbursal_Date__c==null){
                if(Agent_UCVLoanList_Map.get(loan.OwnerId)==null){
                    Agent_UCVLoanList_Map.put(loan.OwnerId,new List<Loan_Account__c>{loan});
                }else{
                    Agent_UCVLoanList_Map.get(loan.OwnerId).add(loan);
                }
            }
            
        }
        
        //calculate wirr of all loan accounts against each agent
        for(id personId:Agent_UCVLoanList_Map.keyset()){
            Decimal Amt_ROI_Mul_Direct = 0;
            Decimal Amt_ROI_Mul_NonDirect = 0;
            Decimal Sum_Amt_Direct = 0;
            Decimal Sum_Amt_NonDirect = 0;
            
            for(Loan_Account__c la:Agent_UCVLoanList_Map.get(personId)){
                    if(la.DSA_Connector__c == null && la.Applicant__r.Loan_Amount__c!=null && la.Applicant__r.Rate_Of_Interest__c!=null){
                        Amt_ROI_Mul_Direct = Amt_ROI_Mul_Direct + (la.Applicant__r.Loan_Amount__c *la.Applicant__r.Rate_Of_Interest__c);
                        Sum_Amt_Direct = Sum_Amt_Direct +la.Applicant__r.Loan_Amount__c;
                        system.debug('loan: '+la.Name);
                    }else if(la.DSA_Connector__c != null && la.Applicant__r.Loan_Amount__c!=null && la.Applicant__r.Rate_Of_Interest__c!=null){
                        system.debug('loan: '+la.Name);
                        Amt_ROI_Mul_NonDirect = Amt_ROI_Mul_NonDirect + (la.Applicant__r.Loan_Amount__c *la.Applicant__r.Rate_Of_Interest__c);
                        Sum_Amt_NonDirect = Sum_Amt_NonDirect+la.Applicant__r.Loan_Amount__c;
                    }
                
            }
            Agent_LoanAmt_UCV_DS_Map.put(personId,Sum_Amt_Direct);
            Agent_LoanAmt_UCV_NDS_Map.put(personId,Sum_Amt_NonDirect);
            Decimal Sum_Amt = Sum_Amt_Direct+Sum_Amt_NonDirect;
            Agent_TotalLoanAmt_UCV_Map.put(personId,Sum_Amt.SetScale(2));
            if(Amt_ROI_Mul_Direct !=0 && Sum_Amt_Direct !=0)
                Agent_WIRR_UCV_DS_Map.put(personId,Amt_ROI_Mul_Direct/Sum_Amt_Direct);
            if(Amt_ROI_Mul_NonDirect !=0 && Sum_Amt_NonDirect !=0)
                Agent_WIRR_UCV_NDS_Map.put(personId,Amt_ROI_Mul_NonDirect/Sum_Amt_NonDirect);
        }
        system.debug('Agent_WIRR_UCV_DS_Map>>'+Agent_WIRR_UCV_DS_Map);
        system.debug('Agent_WIRR_UCV_NDS_Map>>'+Agent_WIRR_UCV_NDS_Map);
        system.debug('Agent_TotalLoanAmt_UCV_Map>>'+Agent_TotalLoanAmt_UCV_Map);
        system.debug('Agent_LoanAmt_UCV_DS_Map>>'+Agent_LoanAmt_UCV_DS_Map);
        system.debug('Agent_LoanAmt_UCV_NDS_Map>>'+Agent_LoanAmt_UCV_NDS_Map);
        //WIRR Calculation ended
        
        //Map of user and role name
        Map<id,string> Agent_Role_Map = new Map<id,string>();
        for(user u:[select id, UserRole.Name FROM User WHERE id=:Agent_UCVLoanList_Map.keyset()]){
            if(String.isNotBlank(u.UserRole.Name))
                Agent_Role_Map.put(u.id,u.UserRole.Name);
        }
        
        //Check for already created incentive for agents
        Map<id,Sales_Incentive__c> Agent_SalesIncentive_Map = new Map<id,Sales_Incentive__c>();
        String year = string.valueOf(System.today().Year());
        List<Sales_Incentive__c> IncentivesList = [select id,Salesperson_Agent__c from Sales_Incentive__c where Salesperson_Agent__c 
                                                   =:Agent_UCVLoanList_Map.keyset() and Month__c=:monthMap.get(System.Today().Month()) AND Year__c=:year];
        if(IncentivesList != null && IncentivesList.size()>0){
            for(Sales_Incentive__c si:IncentivesList){
                Agent_SalesIncentive_Map.put(si.Salesperson_Agent__c,si);
            }
        }
        
        /****** get incentive mapping from metadata and create sales incentive record *******/
        Map<id,Decimal> Agent_TotalIncentive = new Map<id,Decimal>();
        // Direct Sourcing
        Decimal Direct_Sourcing_Incentive = 0;
        for(id personId:Agent_WIRR_UCV_DS_Map.keyset()){
            system.debug('person: '+personId);
            Decimal WIRR = Agent_WIRR_UCV_DS_Map.get(personId);
            system.debug('WIRR: '+WIRR);
            string RoleName = Agent_Role_Map.get(personId);
            system.debug('RoleName: '+RoleName);
            Decimal LoanAmount = Agent_TotalLoanAmt_UCV_Map.get(personId);
            system.debug('LoanAmount: '+LoanAmount);
            List<Incentive_Setup__mdt> Incentive = [select Incentive__c,RecordType__c from Incentive_Setup__mdt where WIRR_Lower_Limit__c <=: WIRR AND WIRR_Higher_Limit__c >=: WIRR AND Product__c ='Lead - UCV' AND Type__c ='Salesperson'
                                                    AND Eligible_Role__c=:RoleName AND Minimum_Amount__c <:LoanAmount AND Maximum_Amount__c >=:LoanAmount AND Sourcing__c ='Direct' AND RecordType__c='Regular Incentive' LIMIT 1];
            if(Incentive != null && Incentive.size()>0 && Incentive[0].Incentive__c !=null){
                system.debug('metadata id: '+Incentive[0].id+'inc: '+Incentive[0].Incentive__c);
                Direct_Sourcing_Incentive = 0.01*Incentive[0].Incentive__c*Agent_LoanAmt_UCV_DS_Map.get(personId);
                Agent_TotalIncentive.put(personId,Direct_Sourcing_Incentive);
            }
        }
        // Non Direct Sourcing
        Decimal NonDirect_Sourcing_Incentive = 0;
        for(id personId:Agent_WIRR_UCV_NDS_Map.keyset()){
            Decimal WIRR = Agent_WIRR_UCV_NDS_Map.get(personId);
            string RoleName = Agent_Role_Map.get(personId);
            Decimal LoanAmount = Agent_TotalLoanAmt_UCV_Map.get(personId);
            List<Incentive_Setup__mdt> Incentive = [select Incentive__c from Incentive_Setup__mdt where WIRR_Lower_Limit__c <=: WIRR AND WIRR_Higher_Limit__c >=: WIRR AND Product__c ='Lead - UCV' AND Type__c ='Salesperson'
                                                    AND Eligible_Role__c=:RoleName AND Minimum_Amount__c <:LoanAmount AND Maximum_Amount__c >:LoanAmount AND Sourcing__c ='Non Direct'AND RecordType__c='Regular Incentive'];
            if(Incentive != null && Incentive.size()>0 && Incentive[0].Incentive__c !=null){
                system.debug('metadata id: '+Incentive[0].id+'inc: '+Incentive[0].Incentive__c);
                NonDirect_Sourcing_Incentive = 0.01*Incentive[0].Incentive__c*Agent_LoanAmt_UCV_NDS_Map.get(personId);
                if(Agent_TotalIncentive.containsKey(personId)){
                    Agent_TotalIncentive.put(personId,Agent_TotalIncentive.get(personId)+NonDirect_Sourcing_Incentive);
                }else{
                    Agent_TotalIncentive.put(personId,NonDirect_Sourcing_Incentive);
                }
            }
        }
        
        for(id personId:Agent_TotalIncentive.keyset()){
            Decimal CappingAmount = Agent_TotalIncentive.get(personId);
            if(Agent_Role_Map.get(personId) =='Sales Manager-UCV' && Agent_TotalIncentive.get(personId) > 35000){
                CappingAmount = 35000;
            }
            else if(Agent_Role_Map.get(personId) =='Sales Officer-UCV' && Agent_TotalIncentive.get(personId) > 22000){
                CappingAmount = 22000;
            }
            if(Agent_SalesIncentive_Map.containskey(personId)){
                Agent_SalesIncentive_Map.get(personId).Incentive_Forecast_For_UCV__c=CappingAmount;
            }else{
                Sales_Incentive__c incent = new Sales_Incentive__c();
                incent.Salesperson_Agent__c = personId;
                incent.Month__c = monthMap.get(system.today().month());
                incent.Year__c = string.valueOf(system.today().Year());
                incent.Incentive_Forecast_For_UCV__c=CappingAmount;
                Agent_SalesIncentive_Map.put(personId,incent);
                
            }
            /*Incentive added for UCV Loans*/
            
           system.debug('Agent_SalesIncentive_Map->'+Agent_SalesIncentive_Map); 
        }
        if(Agent_SalesIncentive_Map != null && Agent_SalesIncentive_Map.size()>0){
            try{
                upsert Agent_SalesIncentive_Map.values();
            }
            catch(dmlException ex){
                system.debug('error: '+ex.getLineNumber() +'>> '+ ex.getMessage());
            }
        }
        
    }
    global void finish(Database.BatchableContext BC){
        
    }
    global void execute(SchedulableContext sc){
        SalesIncentiveUCV_Batch conInstance = new SalesIncentiveUCV_Batch();
        database.executebatch(conInstance);
    }
    
}