unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Office Address</fullName>
                </value>
                <value>
                    <fullName>Residential Address</fullName>
                </value>
                <value>
                    <fullName>Permanent Address</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Area_Destination__c</fullName>
        <label>Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Building_Street_Name_Destination__c</fullName>
        <label>Building / Street Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIBIL_ID_Number__c</fullName>
        <label>CIBIL ID Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIBIL_ID__c</fullName>
        <label>CIBIL ID</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Driving License Number (Permanent only)</fullName>
                </value>
                <value>
                    <fullName>Passport Number</fullName>
                </value>
                <value>
                    <fullName>Voter ID Number</fullName>
                </value>
                <value>
                    <fullName>Pan No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City_Destination__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District_Destination__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flat_House_Number_Destination__c</fullName>
        <label>Flat / House Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Transgender</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pincode_Destination__c</fullName>
        <label>Pincode</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lead - VYAPAR (SECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UDYAM (UNSECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UCV</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Vyapar</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Udyam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Destination__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Secured</fullName>
                </value>
                <value>
                    <fullName>Unsecured</fullName>
                </value>
                <value>
                    <fullName>UCV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/CIBIL_Integration_Test.cls
@isTest
public class CIBIL_Integration_Test {
   
    static testMethod void AcknowledgementRequesttest(){
         //after click on cibil button
             string recordtypeid =Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        string product='Lead - UDYAM (UNSECURED LOAN)';
        string dsaorconnector='DSA';
        string accrecordtypeid=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        
        // create the Dsa Account
        Account acc=TestDataFactory.CreateAccount(accrecordtypeid, dsaorconnector);
           // Create applicant
            Contact c2=TestDataFactory.CreateApplicantbulk(recordtypeid, product,false);
            c2.FirstName = 'Test1';
            c2.LastName = 'Name1';
            c2.Email = 'test1@abc.com';
            c2.MobilePhone = '8790000000';
            c2.Gender__c='Male';
            c2.Loan_Amount__c=7500000;
            c2.Birthdate= date.newInstance(1980, 05, 06);
            c2.CIBIL_ID_Number__c='BKEPS2836K';  
            c2.Address_Type__c='Residential Address';
            c2.Flat_House_Number_Destination__c='DOOR NO-40 FLAT NO-18';
            c2.Building_Street_Name_Destination__c='DOOR NO-40 FLAT NO-18';
            c2.Area_Destination__c='ESWARI RATHNA GARDEN APTS';
            c2.City_Destination__c='CHENNAI';
            c2.Pincode_Destination__c='600032';
            c2.State_Destination__c='TAMIL NADU';
            
        insert c2;
            
        
         Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        //creating user
        User u2 = new User(Alias = 'standt', Email='sakshi1@damcogroup.com',
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                           LocaleSidKey='en_US', ProfileId = p.Id, 
                           TimeZoneSidKey='America/Los_Angeles', UserName='sakshi1@damcogroup.com');
        insert u2;
        system.assert(u2.Id!=null);
        system.runAs(u2){
         contact c=[SELECT id,Loan_Amount__c,Product__c,Gender__c,Birthdate,Name,CIBIL_ID__c,MobilePhone,Address_Type__c,MailingAddress,Flat_House_Number_Destination__c,Building_Street_Name_Destination__c,Area_Destination__c,District_Destination__c,City_Destination__c,
                          State_Destination__c,Pincode_Destination__c,CIBIL_ID_Number__c,Firstname,Lastname,Middlename FROM Contact LIMIT 1];
         system.debug('contact is->'+c);
            
             Test.startTest();
             Test.setMock(HttpCalloutMock.class, new MockHttpResponseAcknowlogement());
            CIBIL_Integration.AcknowledgementRequest(c.Id);
            
            Test.stopTest();
            
        }
        
        
    }

}