unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CIBIL_ID_Number__c</fullName>
        <label>CIBIL ID Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIBIL_ID__c</fullName>
        <label>CIBIL ID</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Driving License Number (Permanent only)</fullName>
                </value>
                <value>
                    <fullName>Passport Number</fullName>
                </value>
                <value>
                    <fullName>Voter ID Number</fullName>
                </value>
                <value>
                    <fullName>Pan No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CIBIL_Score__c</fullName>
        <label>CIBIL Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open - Lead</fullName>
                </value>
                <value>
                    <fullName>Appointment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Appointment Re-schdeduled</fullName>
                </value>
                <value>
                    <fullName>CIBIL Updated</fullName>
                </value>
                <value>
                    <fullName>Under Qualification process</fullName>
                </value>
                <value>
                    <fullName>Documentation in process</fullName>
                </value>
                <value>
                    <fullName>Sales Team Qualified</fullName>
                </value>
                <value>
                    <fullName>SM Queue</fullName>
                </value>
                <value>
                    <fullName>Sales Co-ordinator Queue</fullName>
                </value>
                <value>
                    <fullName>BM Queue</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Not Contactable</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>Document Processing</fullName>
                    <isActive>false</isActive>
                    <label>Document Processing</label>
                </value>
                <value>
                    <fullName>Document Verification</fullName>
                    <isActive>false</isActive>
                    <label>Document Verification</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                    <isActive>false</isActive>
                    <label>Prospecting</label>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                    <isActive>false</isActive>
                    <label>Qualification</label>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <isActive>false</isActive>
                    <label>Qualified</label>
                </value>
                <value>
                    <fullName>Quote Sent</fullName>
                    <isActive>false</isActive>
                    <label>Quote Sent</label>
                </value>
                <value>
                    <fullName>Underwriting</fullName>
                    <isActive>false</isActive>
                    <label>Underwriting</label>
                </value>
                <value>
                    <fullName>Working</fullName>
                    <isActive>false</isActive>
                    <label>Working</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/Cibil_Score_Class.cls
public class Cibil_Score_Class {
    @AuraEnabled
    public static string returnScore(Id AppId){
        system.debug('class called');
        Contact con = [SELECT CIBIL_ID__c,firstName,CIBIL_ID_Number__c FROM Contact WHERE id=:AppId LIMIT 1];
        string msg = '';
        if(string.isBlank(con.firstName))
            msg= 'Please provide First Name';
        else{
            con.CIBIL_ID_Number__c = '1234';
            con.CIBIL_Score__c = 750;
            con.Status__c  = 'CIBIL Updated';
            update con;
            msg = 'Success';  
        }
        return msg;
    }
}