unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Co_Applicant_10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant 10</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Co-Applicant 10)</relationshipLabel>
        <relationshipName>ContactsEOFr</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_11__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant 11</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Co-Applicant 11)</relationshipLabel>
        <relationshipName>ContactsEOGu</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_12__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant 12</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Co-Applicant 12)</relationshipLabel>
        <relationshipName>ContactsEOIW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_13__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant 13</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Co-Applicant 13)</relationshipLabel>
        <relationshipName>ContactsEOLf</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_14__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant 14</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Co-Applicant 14)</relationshipLabel>
        <relationshipName>ContactsEONg</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_15__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant 15</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Co-Applicant 15)</relationshipLabel>
        <relationshipName>ContactsEOOo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Applicant_Type__c</field>
                <operation>equals</operation>
                <value>Co-Applicant</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Co-Applicant)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant 2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Co-Applicant 2)</relationshipLabel>
        <relationshipName>Contacts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant 3</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Co-Applicant 3)</relationshipLabel>
        <relationshipName>Contacts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant 4</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Co-Applicant 4)</relationshipLabel>
        <relationshipName>Contacts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant 5</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Co-Applicant 5)</relationshipLabel>
        <relationshipName>Contacts5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant 6</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Co-Applicant 6)</relationshipLabel>
        <relationshipName>Contacts6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant 7</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Co-Applicant 7)</relationshipLabel>
        <relationshipName>Contacts7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_8__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant 8</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Co-Applicant 8)</relationshipLabel>
        <relationshipName>Contacts8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_9__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant 9</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Co-Applicant 9)</relationshipLabel>
        <relationshipName>Contacts9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Guarantor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor 1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Guarantor 1)</relationshipLabel>
        <relationshipName>ContactsEOQ6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Guarantor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor 2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Guarantor 2)</relationshipLabel>
        <relationshipName>ContactsEOSR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Guarantor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor 3</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Guarantor 3)</relationshipLabel>
        <relationshipName>ContactsEQWj</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Guarantor_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor 4</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Guarantor 4)</relationshipLabel>
        <relationshipName>ContactsEQYf</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Guarantor_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor 5</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Guarantor 5)</relationshipLabel>
        <relationshipName>ContactsEQa2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open - Lead</fullName>
                </value>
                <value>
                    <fullName>Appointment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Appointment Re-schdeduled</fullName>
                </value>
                <value>
                    <fullName>CIBIL Updated</fullName>
                </value>
                <value>
                    <fullName>Under Qualification process</fullName>
                </value>
                <value>
                    <fullName>Documentation in process</fullName>
                </value>
                <value>
                    <fullName>Sales Team Qualified</fullName>
                </value>
                <value>
                    <fullName>SM Queue</fullName>
                </value>
                <value>
                    <fullName>Sales Co-ordinator Queue</fullName>
                </value>
                <value>
                    <fullName>BM Queue</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Not Contactable</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>Document Processing</fullName>
                    <isActive>false</isActive>
                    <label>Document Processing</label>
                </value>
                <value>
                    <fullName>Document Verification</fullName>
                    <isActive>false</isActive>
                    <label>Document Verification</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                    <isActive>false</isActive>
                    <label>Prospecting</label>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                    <isActive>false</isActive>
                    <label>Qualification</label>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <isActive>false</isActive>
                    <label>Qualified</label>
                </value>
                <value>
                    <fullName>Quote Sent</fullName>
                    <isActive>false</isActive>
                    <label>Quote Sent</label>
                </value>
                <value>
                    <fullName>Underwriting</fullName>
                    <isActive>false</isActive>
                    <label>Underwriting</label>
                </value>
                <value>
                    <fullName>Working</fullName>
                    <isActive>false</isActive>
                    <label>Working</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/ValidateApplicantsHandler.cls
public class ValidateApplicantsHandler {
    public static  void validateCoApp(List<Contact> newMap){
        // Insert case 
        List<Contact> newmapCon=[SELECT Id,RecordType.Name,Status__c, Co_Applicant_1__c,Co_Applicant_2__c, Co_Applicant_3__c, Co_Applicant_4__c, Co_Applicant_5__c, Co_Applicant_6__c,
                                 Co_Applicant_7__c, Co_Applicant_8__c, Co_Applicant_9__c, Co_Applicant_10__c, Co_Applicant_11__c, Co_Applicant_12__c,
                                 Co_Applicant_13__c, Co_Applicant_14__c, Co_Applicant_15__c, Guarantor_1__c, Guarantor_2__c, Guarantor_3__c, Guarantor_4__c,
                                 Guarantor_5__c,Co_Applicant_1__r.Pan_Card__c,
                                 Co_Applicant_2__r.Pan_Card__c, Co_Applicant_3__r.Pan_Card__c, Co_Applicant_4__r.Pan_Card__c, 
                                 Co_Applicant_5__r.Pan_Card__c, Co_Applicant_6__r.Pan_Card__c, Co_Applicant_7__r.Pan_Card__c, Co_Applicant_8__r.Pan_Card__c, 
                                 Co_Applicant_9__r.Pan_Card__c, Co_Applicant_10__r.Pan_Card__c, Co_Applicant_11__r.Pan_Card__c, Co_Applicant_12__r.Pan_Card__c,
                                 Co_Applicant_13__r.Pan_Card__c, Co_Applicant_14__r.Pan_Card__c, Co_Applicant_15__r.Pan_Card__c, Guarantor_1__r.Pan_Card__c,
                                 Guarantor_2__r.Pan_Card__c, Guarantor_3__r.Pan_Card__c, Guarantor_4__r.Pan_Card__c, Guarantor_5__r.Pan_Card__c FROM Contact where id in :newMap ];
        for(Contact temp : newmapCon){
            
            if(Schema.SObjectType.Contact.getRecordTypeInfosById().get(temp.RecordTypeid).getname()=='Non Individual' && temp.Status__c=='BM Queue'){
                if(temp.Co_Applicant_1__c !=null){
                    if(temp.Co_Applicant_1__r.Pan_Card__c ==null){
                     
                        temp.Co_Applicant_1__c.addError('Please Update Co-Applicant Pan Card.');
                    }
                }
                if(temp.Co_Applicant_2__c !=null){
                    if(temp.Co_Applicant_2__r.Pan_Card__c ==null){
                        system.debug('Error '+temp.Co_Applicant_1__r.Pan_Card__c);
                        temp.Co_Applicant_2__c.addError('Please Update Co-Applicant Pan Card.');
                    }
                }
            }
        }
    }
    
    
    
}