unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Agent)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Loan_Account__c.object
<CustomObject>
    <description>will be used to store loan and EMI related information</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Loan Accounts (Lead)</relationshipLabel>
        <relationshipName>Loan_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DSA_Connector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DSA/Connector</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Accounts</relationshipLabel>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan Account</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/CreateLoanApplication.cls
public class CreateLoanApplication {
    @InvocableMethod
    public static void CreateLA(List<Contact> ApplicantList){
        if(ApplicantList != null && ApplicantList.size()>0){
            List<Loan_Account__c> toCreateList = new List<Loan_Account__c>();
            for(Contact con:ApplicantList){
                Loan_Account__c la = new Loan_Account__c();
                if(con.Agent__c != null)
                    la.DSA_Connector__c = con.Agent__c;
                la.Applicant__c = con.id;
                la.OwnerId = con.OwnerId;
                toCreateList.add(la);
            }
            if(toCreateList != null && toCreateList.size()>0){
                try{
                    Approval.LockResult[] lrList = Approval.lock(ApplicantList, false);
                    insert toCreateList;
                }
                catch(dmlException ex){
                    system.debug('error: '+ex.getMessage());
                }
            }
        }
    }
}