unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lead - VYAPAR (SECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UDYAM (UNSECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UCV</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Vyapar</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Udyam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open - Lead</fullName>
                </value>
                <value>
                    <fullName>Appointment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Appointment Re-schdeduled</fullName>
                </value>
                <value>
                    <fullName>CIBIL Updated</fullName>
                </value>
                <value>
                    <fullName>Under Qualification process</fullName>
                </value>
                <value>
                    <fullName>Documentation in process</fullName>
                </value>
                <value>
                    <fullName>Sales Team Qualified</fullName>
                </value>
                <value>
                    <fullName>SM Queue</fullName>
                </value>
                <value>
                    <fullName>Sales Co-ordinator Queue</fullName>
                </value>
                <value>
                    <fullName>BM Queue</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Not Contactable</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>Document Processing</fullName>
                    <isActive>false</isActive>
                    <label>Document Processing</label>
                </value>
                <value>
                    <fullName>Document Verification</fullName>
                    <isActive>false</isActive>
                    <label>Document Verification</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                    <isActive>false</isActive>
                    <label>Prospecting</label>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                    <isActive>false</isActive>
                    <label>Qualification</label>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <isActive>false</isActive>
                    <label>Qualified</label>
                </value>
                <value>
                    <fullName>Quote Sent</fullName>
                    <isActive>false</isActive>
                    <label>Quote Sent</label>
                </value>
                <value>
                    <fullName>Underwriting</fullName>
                    <isActive>false</isActive>
                    <label>Underwriting</label>
                </value>
                <value>
                    <fullName>Working</fullName>
                    <isActive>false</isActive>
                    <label>Working</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Meeting__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category </label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DSA</fullName>
                </value>
                <value>
                    <fullName>Connector</fullName>
                </value>
                <value>
                    <fullName>New Customer </fullName>
                </value>
                <value>
                    <fullName>Existing Customer</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Other Referral Source</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meeting_Details__c</fullName>
        <label>Meeting Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Meeting_Outcome__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Rate of Interest Issue</fullName>
                </value>
                <value>
                    <fullName>Loan Amount Issue</fullName>
                </value>
                <value>
                    <fullName>Tenor Issue</fullName>
                </value>
                <value>
                    <fullName>PF Issue</fullName>
                </value>
                <value>
                    <fullName>Insurance Cost</fullName>
                </value>
                <value>
                    <fullName>BT Cost</fullName>
                </value>
                <value>
                    <fullName>Documentation Issue</fullName>
                </value>
                <value>
                    <fullName>Client Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Property not acceptable</fullName>
                </value>
                <value>
                    <fullName>Policy norms not met</fullName>
                </value>
                <value>
                    <fullName>Negative Profile</fullName>
                </value>
                <value>
                    <fullName>Poor RTR</fullName>
                </value>
                <value>
                    <fullName>Poor Banking</fullName>
                </value>
                <value>
                    <fullName>Poor CIBIL</fullName>
                </value>
                <value>
                    <fullName>Rescheduled date</fullName>
                </value>
                <value>
                    <fullName>Rescheduled time</fullName>
                </value>
                <value>
                    <fullName>Customer Interested</fullName>
                </value>
                <value>
                    <fullName>Customer Not Interested</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meeting_Outcome__c</fullName>
        <label>Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Client Not Interested</fullName>
                </value>
                <value>
                    <fullName>Appointment Re-scheduled / Collection pending / Client not met</fullName>
                </value>
                <value>
                    <fullName>Automation to create the meeting plan</fullName>
                </value>
                <value>
                    <fullName>Lead Generation( DSA )</fullName>
                </value>
                <value>
                    <fullName>Lead Generation( Connector )</fullName>
                </value>
                <value>
                    <fullName>Document Collected to fetch CIBIL</fullName>
                </value>
                <value>
                    <fullName>Cat A checklist document collected partially</fullName>
                </value>
                <value>
                    <fullName>Cat A checklist document collected fully</fullName>
                </value>
                <value>
                    <fullName>Sales PD Done</fullName>
                </value>
                <value>
                    <fullName>Property Visit Done</fullName>
                </value>
                <value>
                    <fullName>Pre-Queries given</fullName>
                </value>
                <value>
                    <fullName>Pre-Queries resolved</fullName>
                </value>
                <value>
                    <fullName>Credit PD Visit done</fullName>
                </value>
                <value>
                    <fullName>Post PD Queries given</fullName>
                </value>
                <value>
                    <fullName>Post PD Queries resolved</fullName>
                </value>
                <value>
                    <fullName>Disbursement documentation collected partially</fullName>
                </value>
                <value>
                    <fullName>Disbursement documentation collected fully</fullName>
                </value>
                <value>
                    <fullName>OTC / PDD documents collected partially</fullName>
                </value>
                <value>
                    <fullName>OTC / PDD documents collected fully</fullName>
                </value>
                <value>
                    <fullName>Reference collected</fullName>
                </value>
                <value>
                    <fullName>EMI Partially collected</fullName>
                </value>
                <value>
                    <fullName>EMI fully collected</fullName>
                </value>
                <value>
                    <fullName>PTP</fullName>
                </value>
                <value>
                    <fullName>Lead Generation( Customer )</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Salesperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheduled_Start_Time__c</fullName>
        <label>Scheduled Start Time </label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Re-Scheduled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Collection Task </fullName>
                </value>
                <value>
                    <fullName>Meeting </fullName>
                </value>
                <value>
                    <fullName>Other </fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Meeting</label>
    <nameField>
        <displayFormat>MEET-{0000}</displayFormat>
        <label>Meeting #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Secured</fullName>
                </value>
                <value>
                    <fullName>Unsecured</fullName>
                </value>
                <value>
                    <fullName>UCV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/MeetingTriggerHandler_Test.cls
@istest
public class MeetingTriggerHandler_Test {
    
    public static testmethod void ReScheduled(){
        Contact c = new Contact();
        c.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        c.FirstName = 'Test';
        c.LastName = 'Name';
        c.Email = 'test@abc.com';
        c.Phone = '86559944';
        c.Product__c = 'Lead - VYAPAR (SECURED LOAN)';
        insert c;
        // create meeting
        Meeting__c ma= new Meeting__c();
        ma.Category__c='New Customer';
        ma.Status__c='Scheduled';
        ma.Type__c='Meeting';
        ma.Meeting_Outcome__c='Lead Generation( Customer )';
        ma.Scheduled_Start_Time__c=datetime.newInstance(2021, 6, 2, 20, 45, 0);
        insert ma;
        
        ma.Status__c='Re-Scheduled';
        //ma.Scheduled_Start_Time__c=datetime.newInstance(2021, 3, 30, 8, 45, 0);
        test.startTest();
        try{
            update ma;
        }
        catch (Exception e){
            System.assert(e.getMessage().contains('Please enter a new Scheduled Start Time'));
        }
        
        test.stopTest();
    }
    
    public static testmethod void Scheduled(){
        Contact c = new Contact();
        c.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        c.FirstName = 'Test';
        c.LastName = 'Name';
        c.Email = 'test@abc.com';
        c.Phone = '86559944';
        c.Product__c = 'Lead - VYAPAR (SECURED LOAN)';
        insert c;
        // create meeting
        Meeting__c ma= new Meeting__c();
        ma.Category__c='New Customer';
        ma.Status__c='Scheduled';
        ma.Type__c='Meeting';
        ma.Meeting_Outcome__c='Lead Generation( Customer )';
        ma.Scheduled_Start_Time__c=datetime.newInstance(2021, 6, 2, 20, 45, 0);
        insert ma;
        
        ma.Scheduled_Start_Time__c=datetime.newInstance(2021, 5, 25, 14, 45, 0);
        //ma.Scheduled_Start_Time__c=datetime.newInstance(2021, 3, 30, 8, 45, 0);
        test.startTest();
        try{
            update ma;
        }
        catch (Exception e){
            System.assert(e.getMessage().contains('Scheduled Meeting can not be added in back date'));
        }
        
        test.stopTest();
    }
    
    public static testmethod void completed(){
        Contact c = new Contact();
        c.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        c.FirstName = 'Test';
        c.LastName = 'Name';
        c.Email = 'test@abc.com';
        c.Phone = '86559944';
        c.Product__c = 'Lead - VYAPAR (SECURED LOAN)';
        insert c;
        // create meeting
        Meeting__c ma= new Meeting__c();
        ma.Category__c='New Customer';
        ma.Status__c='Completed';
        ma.Type__c='Meeting';
        ma.Meeting_Outcome__c='Lead Generation( Customer )';
        ma.Scheduled_Start_Time__c=datetime.newInstance(2021, 6, 2, 20, 45, 0);
        insert ma;
        
        ma.Status__c='Scheduled';
        //ma.Scheduled_Start_Time__c=datetime.newInstance(2021, 3, 30, 8, 45, 0);
        test.startTest();
        try{
            update ma;
        }
        catch (Exception e){
            System.assert(e.getMessage().contains('Status of completed meetings cannot be changed'));
        }
        
        test.stopTest();
    }
    
    public static testmethod void completedwith(){
        
        user u1=TestDataFactory.CreateUser();
        System.runAs ( u1 ){
            // create meeting
            Meeting__c ma= new Meeting__c();
            ma.Category__c='New Customer';
            ma.Status__c='Scheduled';
            ma.Type__c='Meeting';
            ma.Meeting_Outcome__c='Lead Generation( Customer )';
            ma.Scheduled_Start_Time__c=datetime.newInstance(2021, 6, 2, 17, 45, 0);
            
            insert ma;
              ma.Status__c='Completed';
            test.startTest();
            try{
                update ma;
            }
            catch (Exception e){
                System.assert(e.getMessage().contains('Meeting Outcome is required to Complete the meeting'));
            }
            
            test.stopTest();
        }
        
    }
    
    public static testmethod void Meetingoutcome(){
        
        user u1=TestDataFactory.CreateUser();
        System.runAs ( u1 ){
            // create meeting
            Meeting__c ma= new Meeting__c();
            ma.Category__c='New Customer';
            ma.Status__c='Scheduled';
            ma.Type__c='Meeting';
            ma.Meeting_Outcome__c='Lead Generation( Customer )';
            ma.Scheduled_Start_Time__c=datetime.newInstance(2021, 6, 2, 17, 45, 0);
   
            
            insert ma;
            
            ma.Meeting_Details__c='Customer Interested';
            test.startTest();
            try{
                update ma;
            }
            catch (Exception e){
                System.assert(e.getMessage().contains('Meeting Outcome can only be captured while completing the meeting'));
            }
            
            test.stopTest();
        }
        
    }
    
    
    public static testmethod void Meetinginsert(){
        
        user u1=TestDataFactory.CreateUser();
        System.runAs ( u1 ){
            // create meeting
            Meeting__c ma= new Meeting__c();
            ma.Category__c='New Customer';
            ma.Status__c='Completed';
            ma.Type__c='Meeting';
            ma.Meeting_Outcome__c='Lead Generation( Customer )';
            ma.Scheduled_Start_Time__c=datetime.newInstance(2021, 6, 2, 17, 45, 0);
            ma.Salesperson__c=u1.Id;
            test.startTest();
            try{
                insert ma;
            }
            catch (Exception e){
                
            } 
            test.stopTest();
        }
        
    }
    
}