unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Branch)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Service Location)</relationshipLabel>
        <relationshipName>Contacts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sourcing_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sourcing Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Sourcing Location)</relationshipLabel>
        <relationshipName>Contacts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/Branch_Update_Handler.cls
public class Branch_Update_Handler {
    
     public static void Branchupdateoninsert(List<contact> newcontact,Id Branchname){
        for(contact con:newcontact){
                  con.Branch__c=Branchname;    
                
            }
        }
     public static void Sourcingupdateoninsert(List<contact> newcontact,Id Sourcingname){
       for(contact con:newcontact){
              con.Sourcing_Location__c=Sourcingname;   
                
            }
        }
 
     public static void Servicingupdateoninsert(List<contact> newcontact,Id Servicingname){
        for(contact con:newcontact){
                con.Service_Location__c=Servicingname;      
                
            }
        }
    
    
    
    }