unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lead - VYAPAR (SECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UDYAM (UNSECURED LOAN)</fullName>
                </value>
                <value>
                    <fullName>Lead - UCV</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Vyapar</fullName>
                </value>
                <value>
                    <fullName>Lead - Rural Udyam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Eligibility_Calculator__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Eligibility Calculator</relationshipLabel>
        <relationshipName>Eligibility_Calculator</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>X15th_of_Month1__c</fullName>
        <label>15th of Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X15th_of_Month2__c</fullName>
        <label>15th of Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X22nd_of_Month1__c</fullName>
        <label>22nd of Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X22nd_of_Month2__c</fullName>
        <label>22nd of Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X27th_of_Month1__c</fullName>
        <label>27th of Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X27th_of_Month2__c</fullName>
        <label>27th of Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X2nd_of_Month1__c</fullName>
        <label>2nd of Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X2nd_of_Month2__c</fullName>
        <label>2nd of Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X8th_of_Month1__c</fullName>
        <label>8th of Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X8th_of_Month2__c</fullName>
        <label>8th of Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Eligibility Calculator</label>
    <nameField>
        <displayFormat>EC-{00000}</displayFormat>
        <label>Eligibility Calculator #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligibility Calculator</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/EligibilityCalculatorTriggerHandler_Test.cls
@isTest
public class EligibilityCalculatorTriggerHandler_Test {
    public static testmethod void testABB(){
        Contact c = new Contact();
        c.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        c.FirstName = 'Test';
        c.LastName = 'Name';
        c.Email = 'test@abc.com';
        c.Phone = '86559944';
        c.Product__c = 'Lead - VYAPAR (SECURED LOAN)';
        insert c;
        
        Eligibility_Calculator__c ec = new Eligibility_Calculator__c();
        ec.Applicant__c = c.id;
        ec.X2nd_of_Month1__c = 100;
        ec.X8th_of_Month1__c = 110;
        ec.X15th_of_Month1__c = 110;
        ec.X22nd_of_Month1__c = 120;
        ec.X27th_of_Month1__c = 130;
        ec.X2nd_of_Month2__c = 100;
        ec.X8th_of_Month2__c = 110;
        ec.X15th_of_Month2__c = 110;
        ec.X22nd_of_Month2__c = 120;
        ec.X27th_of_Month2__c = 130;
        insert ec;
        
    }
}