unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Applicant_Father_Name__c</fullName>
        <label>Applicant Father Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <label>Applicant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Co-Applicant</fullName>
                </value>
                <value>
                    <fullName>Guarantor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Form_Type__c</fullName>
        <label>Application Form Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Physical Application Form</fullName>
                </value>
                <value>
                    <fullName>E-Application Form</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Area_Destination__c</fullName>
        <label>Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Area_Mailing__c</fullName>
        <label>Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorised_Person__c</fullName>
        <label>Authorised Person</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Building_Street_Name_Destination__c</fullName>
        <label>Building / Street Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Building_Street_Name_Mailing__c</fullName>
        <label>Building / Street Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIBIL_ID__c</fullName>
        <label>CIBIL ID</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Driving License Number (Permanent only)</fullName>
                </value>
                <value>
                    <fullName>Passport Number</fullName>
                </value>
                <value>
                    <fullName>Voter ID Number</fullName>
                </value>
                <value>
                    <fullName>Pan No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Type__c</fullName>
        <label>Company Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MSME</fullName>
                </value>
                <value>
                    <fullName>Non MSME</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Constitution__c</fullName>
        <label>Constitution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Proprietership</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Private Limited</fullName>
                </value>
                <value>
                    <fullName>LLP</fullName>
                </value>
                <value>
                    <fullName>Public Limited</fullName>
                </value>
                <value>
                    <fullName>Society</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>SEP</fullName>
                </value>
                <value>
                    <fullName>SENP</fullName>
                </value>
                <value>
                    <fullName>Salaried</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Incorporation__c</fullName>
        <label>Date of Incorporation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>District_Destination__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District_Mailing__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Graduate</fullName>
                </value>
                <value>
                    <fullName>Post Graduate</fullName>
                </value>
                <value>
                    <fullName>Under Graduate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flat_House_Number_Destination__c</fullName>
        <label>Flat / House Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flat_House_Number_Mailing__c</fullName>
        <label>Flat / House Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_60_Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Form 60 Uploaded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Transgender</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marital_Status__c</fullName>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single</fullName>
                </value>
                <value>
                    <fullName>Married</fullName>
                </value>
                <value>
                    <fullName>Divorced</fullName>
                </value>
                <value>
                    <fullName>Widowed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nature_of_Loan__c</fullName>
        <label>Nature of Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Refinance</fullName>
                </value>
                <value>
                    <fullName>Repurchase</fullName>
                </value>
                <value>
                    <fullName>Internal BT</fullName>
                </value>
                <value>
                    <fullName>External BT plus Top-up</fullName>
                </value>
                <value>
                    <fullName>Fresh Loan</fullName>
                </value>
                <value>
                    <fullName>Purchase of Commercial Property</fullName>
                </value>
                <value>
                    <fullName>Top-Up Loan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_of_Years_in_Business__c</fullName>
        <label>No of Years in Business</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Occupancy_Status__c</fullName>
        <label>Occupancy Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Owned</fullName>
                </value>
                <value>
                    <fullName>Rental</fullName>
                </value>
                <value>
                    <fullName>Parental</fullName>
                </value>
                <value>
                    <fullName>Co-Provided</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pincode_Destination__c</fullName>
        <label>Pincode</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pincode_Mailing__c</fullName>
        <label>Pincode</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_with_Applicant__c</fullName>
        <label>Relationship with Applicant</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Same_As_Destination_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Same As Destination Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hot</fullName>
                </value>
                <value>
                    <fullName>Cold</fullName>
                </value>
                <value>
                    <fullName>Warm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open - Lead</fullName>
                </value>
                <value>
                    <fullName>Appointment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Appointment Re-schdeduled</fullName>
                </value>
                <value>
                    <fullName>CIBIL Updated</fullName>
                </value>
                <value>
                    <fullName>Under Qualification process</fullName>
                </value>
                <value>
                    <fullName>Documentation in process</fullName>
                </value>
                <value>
                    <fullName>Sales Team Qualified</fullName>
                </value>
                <value>
                    <fullName>SM Queue</fullName>
                </value>
                <value>
                    <fullName>Sales Co-ordinator Queue</fullName>
                </value>
                <value>
                    <fullName>BM Queue</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Not Contactable</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>Document Processing</fullName>
                    <isActive>false</isActive>
                    <label>Document Processing</label>
                </value>
                <value>
                    <fullName>Document Verification</fullName>
                    <isActive>false</isActive>
                    <label>Document Verification</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                    <isActive>false</isActive>
                    <label>Prospecting</label>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                    <isActive>false</isActive>
                    <label>Qualification</label>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <isActive>false</isActive>
                    <label>Qualified</label>
                </value>
                <value>
                    <fullName>Quote Sent</fullName>
                    <isActive>false</isActive>
                    <label>Quote Sent</label>
                </value>
                <value>
                    <fullName>Underwriting</fullName>
                    <isActive>false</isActive>
                    <label>Underwriting</label>
                </value>
                <value>
                    <fullName>Working</fullName>
                    <isActive>false</isActive>
                    <label>Working</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_At_Address_In_Years__c</fullName>
        <label>Time At Address (In Years)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/Validation_on_Co_Applicant.cls
public class Validation_on_Co_Applicant {
    
    public static void validationcheckonCo_Applicant(List<contact> newcontact){
        string recordtypeid1 =Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        string recordtypeid2 =Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Non Individual').getRecordTypeId();
        
        for(contact con:newcontact){
            
            if((con.Applicant_Type__c=='CO-APPLICANT' || con.Applicant_Type__c=='GUARANTOR') && (con.RecordTypeId==Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Non Individual').getRecordTypeId()) && con.Status__c=='CIBIL Updated'){
                
                
                if(con.Company_Type__c==null){
                    
                    con.addError('Please Enter the Company Type');
                    
                }
                if(con.Constitution__c==null){
                    
                    con.addError('Please Enter the Constitution');
                    
                }
                if(con.Date_of_Incorporation__c==null){
                    
                    con.addError('Please Enter the Date of Incorporation');
                    
                }
                if(con.No_of_Years_in_Business__c==null){
                    
                    con.addError('Please Enter the No of Years in Business');
                    
                }
                if(con.GST_Applicable__c==null){
                    
                    con.addError('Please Enter the GST Applicable');
                    
                }
                if(con.Segment__c==null){
                    
                    con.addError('Please Enter the Segment');
                    
                }
                if(con.Type_of_Business__c==null){
                    
                    con.addError('Please Enter the Type of Business');
                    
                }
                if(con.Cluster__c==null){
                    
                    con.addError('Please Enter the Cluster');
                    
                }
                if(con.Customer_Type__c==null){
                    
                    con.addError('Please Enter the Customer Type');
                    
                }
                if(con.Relationship_with_Applicant__c==null){
                    
                    con.addError('Please Enter the Relationship with Applicant');
                    
                }
                if(con.Time_At_Address_In_Years__c==null){
                    
                    con.addError('Please Enter the Time At Address In Years ');
                    
                }
                if(con.Nature_of_Loan__c==null){
                    
                    con.addError('Please Enter the Nature of Loan ');
                    
                }
                if(con.Occupancy_Status__c==null){
                    
                    con.addError('Please Enter the Occupancy Status');
                    
                }
                if(con.Email==null){
                    
                    con.addError('Please Enter the Email');
                    
                }
                if(con.Stage__c==null){
                    
                    con.addError('Please Enter the Stage');
                    
                }
                if(con.Authorised_Person__c==null){
                    
                    con.addError('Please Enter the Authorised Person');
                    
                }
                if(con.Flat_House_Number_Office__c==null){
                    
                    con.addError('Please Enter the Office Flat House Number');
                    
                }
                if(con.Building_Street_Name_Office__c==null){
                    
                    con.addError('Please Enter the Office Building Street Name');
                    
                }
                if(con.Area_Office__c==null){
                    
                    con.addError('Please Enter the Office Area');
                    
                }
                if(con.District_Office__c==null){
                    
                    con.addError('Please Enter the Office District');
                    
                }
                
                if(con.Pincode_Office__c==null){
                    
                    con.addError('Please Enter the Office Pincode');
                    
                }
                if(con.Same_As_Current_Address__c!=true){
                    
                    if(con.Flat_House_Number_Mailing__c==null){
                        
                        con.addError('Please Enter the PERMANENT Flat House Number');
                        
                    }
                    if(con.Building_Street_Name_Mailing__c==null){
                        
                        con.addError('Please Enter the PERMANENT Building Street Name');
                        
                    }
                    if(con.Area_Mailing__c==null){
                        
                        con.addError('Please Enter the PERMANENT Area');
                        
                    }
                    if(con.District_Mailing__c==null){
                        
                        con.addError('Please Enter the PERMANENT District');
                        
                    }
                    
                    if(con.Pincode_Mailing__c==null){
                        
                        con.addError('Please Enter the PERMANENT Pincode');
                        
                    }
                    
                }
                
                if(con.Status__c=='Prospect'){
                    
                    con.addError('CO-APPLICANT/GUARANTOR Status Should be CIBIL Updated ');
                    
                }
            }
            
            if((con.Applicant_Type__c=='CO-APPLICANT' || con.Applicant_Type__c=='GUARANTOR') && (con.RecordTypeId==Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId()) && con.Status__c=='CIBIL Updated'){
                
                
                
                if(con.Birthdate==null){
                    
                    con.addError('Please Enter the Birthdate');
                    
                }
                if(con.Gender__c==null){
                    
                    con.addError('Please Enter the Gender');
                    
                }
                if(con.Education__c==null){
                    
                    con.addError('Please Enter the Education');
                    
                }
                if(con.Marital_Status__c==null){
                    
                    con.addError('Please Enter the Marital Status');
                    
                }
                if(con.GST_Applicable__c==null){
                    
                    con.addError('Please Enter the GST Applicable');
                    
                }
                if(con.Segment__c==null){
                    
                    con.addError('Please Enter the Segment');
                    
                }
                if(con.Type_of_Business__c==null){
                    
                    con.addError('Please Enter the Type of Business');
                    
                }
                if(con.Cluster__c==null){
                    
                    con.addError('Please Enter the Cluster');
                    
                }
                if(con.Customer_Type__c==null){
                    
                    con.addError('Please Enter the Customer Type');
                    
                }
                if(con.Relationship_with_Applicant__c==null){
                    
                    con.addError('Please Enter the Relationship with Applicant');
                    
                }
                if(con.Time_At_Address_In_Years__c==null){
                    
                    con.addError('Please Enter the Time At Address In Years ');
                    
                }
                if(con.Nature_of_Loan__c==null){
                    
                    con.addError('Please Enter the Nature of Loan ');
                    
                }
                if(con.Occupancy_Status__c==null){
                    
                    con.addError('Please Enter the Occupancy Status');
                    
                }
                if(con.Email==null){
                    
                    con.addError('Please Enter the Email');
                    
                }
                if(con.Stage__c==null){
                    
                    con.addError('Please Enter the Stage');
                    
                }
                if(con.Authorised_Person__c==null){
                    
                    con.addError('Please Enter the Authorised Person');
                    
                }
                if(con.Company_Name__c==null){
                    
                    con.addError('Please Enter the Company Name');
                    
                }
                if(con.Applicant_Father_Name__c==null){
                    
                    con.addError('Please Enter the Applicant Father Name');
                    
                }
                if(con.Form_60_Uploaded__c==false){
                    
                    con.addError('Please Enter the Physical Application form uploaded');
                    
                }
                if(con.Flat_House_Number_Office__c==null){
                    
                    con.addError('Please Enter the Office Flat House Number');
                    
                }
                if(con.Building_Street_Name_Office__c==null){
                    
                    con.addError('Please Enter the Office Building Street Name');
                    
                }
                if(con.Area_Office__c==null){
                    
                    con.addError('Please Enter the Office Area');
                    
                }
                if(con.District_Office__c==null){
                    
                    con.addError('Please Enter the Office District');
                    
                }
                
                if(con.Pincode_Office__c==null){
                    
                    con.addError('Please Enter the Office Pincode');
                    
                }
                if(con.Same_As_Current_Address__c!=true){
                    
                    if(con.Flat_House_Number_Mailing__c==null){
                        
                        con.addError('Please Enter the PERMANENT Flat House Number');
                        
                    }
                    if(con.Building_Street_Name_Mailing__c==null){
                        
                        con.addError('Please Enter the PERMANENT Building Street Name');
                        
                    }
                    if(con.Area_Mailing__c==null){
                        
                        con.addError('Please Enter the PERMANENT Area');
                        
                    }
                    if(con.District_Mailing__c==null){
                        
                        con.addError('Please Enter the PERMANENT District');
                        
                    }
                    
                    if(con.Pincode_Mailing__c==null){
                        
                        con.addError('Please Enter the PERMANENT Pincode');
                        
                    }
                    
                }
                if(con.Same_As_Destination_Address__c!=true){
                    
                    if(con.Flat_House_Number_Destination__c==null){
                        
                        con.addError('Please Enter the Residence Flat House Number');
                        
                    }
                    if(con.Building_Street_Name_Destination__c==null){
                        
                        con.addError('Please Enter the Residence Building Street Name');
                        
                    }
                    if(con.Area_Destination__c==null){
                        
                        con.addError('Please Enter the Residence Area');
                        
                    }
                    if(con.District_Destination__c==null){
                        
                        con.addError('Please Enter the Residence District');
                        
                    }
                    
                    if(con.Pincode_Destination__c==null){
                        
                        con.addError('Please Enter the Residence Pincode');
                        
                    }
                    
                }
                if(con.Application_Form_Type__c==null){
                    
                    con.addError('Please Enter the Application Form Type');
                    
                }
                
                if(con.Consent_Received_From_Applicant__c==null){
                    
                    con.addError('Please Enter the Signed Consent Received');
                    
                }
                if(con.CIBIL_ID__c==null){
                    
                    con.addError('Please Enter the CIBIL ID');
                    
                }
                if(con.CIBIL_ID_Number__c==null){
                    
                    con.addError('Please Enter the CIBIL ID Number');
                    
                }
                if(con.CIBIL_Score__c==null){
                    
                    con.addError('Please Enter the CIBIL Score');
                    
                }
                if(con.CIBIL_SCORE_DATE__c==null){
                    
                    con.addError('Please Enter the CIBIL Score Date');
                    
                }
                 if(con.CIBIL_ID_Upload__c!=True){
                    
                    con.addError('Please Enter the CIBIL Document Uploaded');
                    
                }
                if(con.Product__c==Null){
                    
                    con.addError('Please Enter the Product');
                    
                }
                if(con.Loan_Amount__c==Null){
                    
                    con.addError('Please Enter the Loan Amount');
                    
                }
                 if(con.Status__c=='Prospect'){
                    
                    con.addError('CO-APPLICANT/GUARANTOR Status Should be CIBIL Updated ');
                    
                }
                
            }
            
        }
    }
    
}