unpackaged/objects/Eligibility_Calculator__c.object
<CustomObject>
    <fields>
        <fullName>ABB__c</fullName>
        <inlineHelpText>Choose lower of the 3 months and add</inlineHelpText>
        <label>ABB</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Average_Monthly_Balance_1__c</fullName>
        <formula>(X2nd_of_Month1__c + X8th_of_Month1__c + X15th_of_Month1__c + X22nd_of_Month1__c + X27th_of_Month1__c)/5</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Average Monthly Balance 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Average_Monthly_Balance_2__c</fullName>
        <formula>(X2nd_of_Month2__c + X8th_of_Month2__c + X15th_of_Month2__c + X22nd_of_Month2__c + X27th_of_Month2__c)/5</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Average Monthly Balance 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Average_Monthly_Balance_3__c</fullName>
        <formula>(X2nd_of_Month3__c + X8th_of_Month3__c + X15th_of_Month3__c + X22nd_of_Month3__c + X27th_of_Month3__c)/5</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Average Monthly Balance 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Average_Monthly_Balance_4__c</fullName>
        <formula>(X2nd_of_Month4__c + X8th_of_Month4__c + X15th_of_Month4__c + X22nd_of_Month4__c + X27th_of_Month4__c)/5</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Average Monthly Balance 4</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Average_Monthly_Balance_5__c</fullName>
        <formula>(X2nd_of_Month5__c + X8th_of_Month5__c + X15th_of_Month5__c + X22nd_of_Month5__c + X27th_of_Month5__c)/5</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Average Monthly Balance 5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Average_Monthly_Balance_6__c</fullName>
        <formula>(X2nd_of_Month6__c + X8th_of_Month6__c + X15th_of_Month6__c + X22nd_of_Month6__c + X27th_of_Month6__c)/5</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Average Monthly Balance 6</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Eligibility Calculator</label>
    <nameField>
        <displayFormat>EC-{00000}</displayFormat>
        <label>Eligibility Calculator #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligibility Calculator</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/EligibilityCalculatorTriggerHandler.cls
public class EligibilityCalculatorTriggerHandler {
	
    public static void calculateABB(List<Eligibility_Calculator__c> ECList){
        decimal avg1 = 0;
        decimal avg2 = 0;
        decimal avg3 = 0;
        decimal avg4 = 0;
        decimal avg5 = 0;
        decimal avg6 = 0;
        
        for(Eligibility_Calculator__c ec:ECList){
            if(ec.Average_Monthly_Balance_1__c != null)
                avg1 = ec.Average_Monthly_Balance_1__c;
            if(ec.Average_Monthly_Balance_2__c != null)
                avg2 = ec.Average_Monthly_Balance_2__c;
            if(ec.Average_Monthly_Balance_3__c != null)
                avg3 = ec.Average_Monthly_Balance_3__c;
            if(ec.Average_Monthly_Balance_4__c != null)
                avg4 = ec.Average_Monthly_Balance_4__c;
            if(ec.Average_Monthly_Balance_5__c != null)
                avg5 = ec.Average_Monthly_Balance_5__c;
            if(ec.Average_Monthly_Balance_6__c != null)
                avg6 = ec.Average_Monthly_Balance_6__c;
            Decimal[] avgArray= new Decimal[] {avg1,avg2,avg3,avg4,avg5,avg6};
                system.debug('unsorted>>'+avgArray);
                avgArray.sort();
            system.debug('sorted>>'+avgArray);
            ec.ABB__c = (avgArray[0]+avgArray[1]+avgArray[2])/3;
        }
    }
}