unpackaged/objects/Loan_Account__c.object
<CustomObject>
    <description>will be used to store loan and EMI related information</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Loan Accounts (Lead)</relationshipLabel>
        <relationshipName>Loan_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LOAN_STATUS__c</fullName>
        <label>LOAN STATUS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prospect_ID__c</fullName>
        <label>Prospect ID</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <label>Loan Account</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Loan_API__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>FORMNO__c</fullName>
        <label>FORMNO</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UNIQUE_REQUEST_ID__c</fullName>
        <label>UNIQUE_REQUEST_ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Loan API</label>
</CustomObject>

unpackaged/objects/LOAN_AUTHENTICATION__mdt.object
<CustomObject>
    <fields>
        <fullName>FORMNO__c</fullName>
        <label>FORMNO</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Get_loan_details__c</fullName>
        <label>Get loan details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_TAT__c</fullName>
        <label>Loan TAT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNIQUE_REQUEST_ID__c</fullName>
        <label>UNIQUE_REQUEST_ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>LOAN AUTHENTICATION</label>
    <pluralLabel>LOAN AUTHENTICATIONS</pluralLabel>
</CustomObject>

unpackaged/objects/Loan_TAT__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>UNIQUE_REQUEST_ID__c</fullName>
        <label>UNIQUE_REQUEST_ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Loan TAT</label>
</CustomObject>

unpackaged/classes/Sync_Loan_Account.cls
global  class Sync_Loan_Account {
    
    @AuraEnabled
    global  static string LoanDetailRequest(Id loanId){
        
        system.debug('class called');
        set<string> loan_status= new set<string>();
        string AUTHENTICATION;
        string BASICINFO;
        string token;
        String Final_json;
        String endpoint;
        string PROSPECT_DETAILS;
        string UNIQUE_REQUEST_ID;
        list<LOAN_AUTHENTICATION__mdt> LoanAuth=new list<LOAN_AUTHENTICATION__mdt>();
        list<Loan_Account__c> loan =[SELECT id,Applicant_Code__c,Applicant__r.name,LOAN_STATUS__c,
                                     Prospect_Code__c,Prospect_ID__c FROM Loan_Account__c WHERE id=:loanId LIMIT 1];
        for(Loan_Account__c la : loan){
            if(la.LOAN_STATUS__c=='Disbursed'){
                
                token=Loan_Creation.AUTHENTICATION();
                //Get UNIQUE_REQUEST_ID
                
                // Geeting UNIQUE_REQUEST_ID,FORMNO value from custom setting.
                list<Loan_API__c> Loanunqno=[select UNIQUE_REQUEST_ID__c,FORMNO__c from Loan_API__c Limit 1];      
                UNIQUE_REQUEST_ID= string.valueOf(Loanunqno[0].UNIQUE_REQUEST_ID__c);    
                
                // AUTHENTICATION details
                AUTHENTICATION= '{"AUTHENTICATION":';
                AUTHENTICATION+='{"TOKEN":"'+token+'",';
                AUTHENTICATION+='"UNIQUE_REQUEST_ID":"'+UNIQUE_REQUEST_ID+'",';
                AUTHENTICATION+='"DEVICE_ID":"SALES_FORCE"},';
                // PROSPECT_DETAILS 
                BASICINFO='"BASICINFO":{';
                BASICINFO+=' "IS_PROSPECT": "Y",';
                BASICINFO+='"RULE_ID": "",';
                BASICINFO+='"PROSPECT_CODE":"'+la.Prospect_Code__c+'"}';
                Final_json=AUTHENTICATION+BASICINFO+'}';
                system.debug('Final_json->'+Final_json);
                
                LoanAuth=[select Get_loan_details__c from LOAN_AUTHENTICATION__mdt Limit 1];
                endpoint=LoanAuth[0].Get_loan_details__c;  
                HttpRequest req = new HttpRequest();
                req.setHeader('Accept', '*/*');
                req.setHeader('Content-Type', 'application/json;charset=UTF-8');
                req.setEndpoint(endpoint);
                req.setMethod('POST');
                req.setbody(Final_json);
                Http http = new Http();
                HTTPResponse response = http.send(req); 
                string responsebody = response.getBody();
                system.debug('loanresponse->'+responsebody);
                
                
            }
            else{
                token=Loan_Creation.AUTHENTICATION();
                //Get UNIQUE_REQUEST_ID
                
                // Geeting UNIQUE_REQUEST_ID,FORMNO value from custom setting.
                list<Loan_API__c> Loanunqno=[select UNIQUE_REQUEST_ID__c,FORMNO__c from Loan_API__c Limit 1];      
                UNIQUE_REQUEST_ID= string.valueOf(Loanunqno[0].UNIQUE_REQUEST_ID__c);    
                
                // AUTHENTICATION details
                AUTHENTICATION= '{"AUTHENTICATION":';
                AUTHENTICATION+='{"TOKEN":"'+token+'",';
                AUTHENTICATION+='"UNIQUE_REQUEST_ID":"'+UNIQUE_REQUEST_ID+'",';
                AUTHENTICATION+='"DEVICE_ID":"SALES_FORCE"},';
                // PROSPECT_DETAILS 
                PROSPECT_DETAILS='"PROSPECT_DETAILS":{';
                PROSPECT_DETAILS+='"PROSPECT_CODE":"'+la.Prospect_Code__c+'"}';
                
                Final_json=AUTHENTICATION+PROSPECT_DETAILS+'}';
                LoanAuth=[select Loan_TAT__c from LOAN_AUTHENTICATION__mdt Limit 1];
                endpoint=LoanAuth[0].Loan_TAT__c;  
                HttpRequest req = new HttpRequest();
                req.setHeader('Accept', '*/*');
                req.setHeader('Content-Type', 'application/json;charset=UTF-8');
                req.setEndpoint(endpoint);
                req.setMethod('POST');
                req.setbody(Final_json);
                Http http = new Http();
                HTTPResponse response = http.send(req); 
                string responsebody = response.getBody();
                system.debug('loanresponse->'+responsebody);
                
            }
            
            
        }
        
        
        return null;
        
        
        
    }
    
}