unpackaged/objects/Meeting__c.object
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <displayFormat>MEET-{0000}</displayFormat>
        <label>Meeting #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Meeting_Rating__c.object
<CustomObject>
    <fields>
        <fullName>Feeback__c</fullName>
        <label>Feeback</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipLabel>Meeting Ratings</relationshipLabel>
        <relationshipName>Meeting_Ratings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Meeting Rating</label>
    <nameField>
        <displayFormat>MR-{0000}</displayFormat>
        <label>Meeting Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/MeetingFeedback_CTR.cls
public class MeetingFeedback_CTR {
    public String MeetingId {get;set;}
    public string feedbackcheck{get;set;}
    public Integer rating { get; set; }
    public string response{ get; set; }
    List<Meeting_Rating__c> MeetingList;
    public MeetingFeedback_CTR () {
        MeetingId = ApexPages.currentPage().getParameters().get('id');
        feedbackcheck= 'False';
        response='False';
    }
    public PageReference InitPage() {
        MeetingList=[select id,Name,Meeting__c FROM  Meeting_Rating__c WHERE Meeting__c=:MeetingId];
        if(MeetingList.size()>0){
          response='True';
          feedbackcheck='True';
        }
        return null;		
    }
    
    public PageReference save(){
        system.debug('selected rating>>>>>'+rating);
        if(rating!=null){
            Meeting_Rating__c mr=new Meeting_Rating__c();
            mr.Meeting__c=MeetingId;
            mr.Feeback__c=string.valueOf(rating);
            insert mr;
            feedbackcheck='True';
        }
        if(rating==null){
         feedbackcheck='False';   
        }
        
        
        return null;
        
    }
}