unpackaged/objects/Sales_Incentive__c.object
<CustomObject>
    <fields>
        <fullName>Incentive_for_Secured_Loans__c</fullName>
        <label>Incentive for Secured Loans</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Incentive_for_Unsecured_Loans__c</fullName>
        <label>Incentive for Unsecured Loans</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Incentive</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Incentives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/SaleIncentive_Trigger_Test.cls
@isTest
public class SaleIncentive_Trigger_Test {
    public static testmethod void test1(){
      
      Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        //creating user
        User u = new User(Alias = 'standt', Email='demouser1@damcogroup.com',
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                           LocaleSidKey='en_US', ProfileId = p.Id, 
                           TimeZoneSidKey='America/Los_Angeles', UserName='demouser1@damcogroup.com.ambit');
        insert u;
      
      Sales_Incentive__c sa = new Sales_Incentive__c();
        sa.Incentive_for_Secured_Loans__c=1234.00;
       sa.Incentive_for_Unsecured_Loans__c=25000.00;
       insert sa;
      
      
  }

}