unpackaged/objects/Sales_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_of_Logins__c</fullName>
        <label>No of Files Logged In (No)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_disbursement__c</fullName>
        <label>No.of Units Disbursed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <inlineHelpText>Format like- 2021</inlineHelpText>
        <label>Year</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>volume_of_disbursement__c</fullName>
        <label>volume of Units Disbursed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Weekly Sales Plan</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Sales Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weekly Sales Plan</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/User_Statistics__c.object
<CustomObject>
    <fields>
        <fullName>Login_Commitment_for_the_month__c</fullName>
        <label>Login Commitment for the month</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_of_Disbursement__c</fullName>
        <label>No. of Disbursement</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Logins__c</fullName>
        <label>No. of Logins</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Salesperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserStatistics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value_of_Disbursement_Commitment_For_the__c</fullName>
        <label>VOD Commitment For The Month</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Statistics</label>
    <nameField>
        <displayFormat>US-{000000}</displayFormat>
        <label>User Statistics #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Statistics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/Sales_plan_User_StatisticsHelper.cls
public class Sales_plan_User_StatisticsHelper {
    
    public static void insertUpdateUser_Statistics(Set<Id> SalesPlanList)
    {
        Set<Id> Salespersons=new Set<Id>();
        Set<string> SalespersonsData=new Set<string>();
        Set<string> SalespersonsUSData=new Set<string>();
        set<String> usermonth=new set<String>();
        set<String> userYear=new set<String>();
        List<User_Statistics__c> insertUser_Statistics=new List<User_Statistics__c>();
        List<User_Statistics__c> UpdateUser_Statistics=new List<User_Statistics__c>();
        List<Sales_Plan__c> SalesPlanlst=new List<Sales_Plan__c>();
        
        Map<String,User_Statistics__c> MapUser_Statistics= new  Map<String,User_Statistics__c>();
        for(Sales_Plan__c SalesPlan:[select Id,OwnerId , No_of_Logins__c,No_of_disbursement__c, Year__c, Month__c FROM Sales_Plan__c where id in:SalesPlanList ])
        {
            Salespersons.add(SalesPlan.ownerid);
            
            SalespersonsData.add(SalesPlan.ownerid+'-'+SalesPlan.Month__c.toUppercase()+'-'+SalesPlan.Year__c.toUppercase());
            usermonth.add(SalesPlan.Month__c);
            userYear.add(SalesPlan.Year__c);
            SalesPlanlst.add(SalesPlan);
            
        }
        AggregateResult[]  SalesPlanGroupedData=[select  ownerid,sum(No_of_Logins__c) No_of_Logins__c,sum(volume_of_disbursement__c) volume_of_disbursement__c , Year__c, Month__c FROM Sales_Plan__c where id in:SalesPlanList group by ownerid, Year__c, Month__c];
        
        
        List<User_Statistics__c>  User_Statistics=[SELECT Id, Salesperson__c,Month__c, Year__c FROM User_Statistics__c where Salesperson__c in:Salespersons and Month__c in:usermonth and Year__c in:userYear ];
        for(User_Statistics__c UserStatistics:User_Statistics)
        {
            MapUser_Statistics.put(UserStatistics.Salesperson__c+'-'+UserStatistics.Month__c.toUppercase()+'-'+UserStatistics.Year__c.toUppercase(),UserStatistics);
            
        }
        for(AggregateResult SalesPlan:SalesPlanGroupedData)
        {
            if(MapUser_Statistics.containskey(SalesPlan.get('ownerid')+'-'+SalesPlan.get('Month__c').toString().toUppercase()+'-'+SalesPlan.get('Year__c').toString().toUppercase()))
            {
                User_Statistics__c updUser_Statistics =  updateUS(SalesPlan,MapUser_Statistics.get(SalesPlan.get('ownerid')+'-'+SalesPlan.get('Month__c').toString().toUppercase()+'-'+SalesPlan.get('Year__c').toString().toUppercase()).Id);
                UpdateUser_Statistics.add(updUser_Statistics);
            }
            else
            {
                User_Statistics__c instUser_Statistics =insertUS(SalesPlan);
                insertUser_Statistics.add(instUser_Statistics);
            }
            
        }
        if(!insertUser_Statistics.isEmpty())
        {
            try{
                insert insertUser_Statistics;
            }Catch(Exception Ex)
            {
                System.debug('----Error-----'+Ex.getMessage()+' @ Line No '+Ex.getLineNumber());
            }
        }
        if(!UpdateUser_Statistics.isEmpty())
        {
            try{
                update UpdateUser_Statistics;
            }Catch(Exception Ex)
            {
                System.debug('----Error-----'+Ex.getMessage()+' @ Line No '+Ex.getLineNumber());
            }
        }
    }
    public static User_Statistics__c updateUS(AggregateResult SalesPlan, Id Usid)
    {
        User_Statistics__c objUser_Statistics=new User_Statistics__c(Id=Usid,Salesperson__c=SalesPlan.get('ownerid').tostring(),Login_Commitment_for_the_month__c=(decimal)SalesPlan.get('No_of_Logins__c'),
                                                                     Value_of_Disbursement_Commitment_For_the__c=(decimal)SalesPlan.get('volume_of_disbursement__c')
                                                                    );
        
        
        return objUser_Statistics;
        
    }
    public static User_Statistics__c insertUS(AggregateResult SalesPlan)
    {
        User_Statistics__c objUser_Statistics=new User_Statistics__c(Salesperson__c=SalesPlan.get('ownerid').tostring(),
                                                                     Login_Commitment_for_the_month__c=(decimal)SalesPlan.get('No_of_Logins__c'),
                                                                     Value_of_Disbursement_Commitment_For_the__c=(decimal)SalesPlan.get('volume_of_disbursement__c'),
                                                                     Month__c=SalesPlan.get('Month__c').tostring(),Year__c=SalesPlan.get('Year__c').tostring());
        
        return objUser_Statistics;
    }
    
}